
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Foundation.ErrorHandling
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ErrorHandlingConfigurationItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("8148e537-118d-4f13-b6e4-c70036c5b915");
							public static class FieldIds
		{

			public static readonly string _404PageLocation = "be5681b8-5cd7-429e-8676-dd9c73ea965c";
}

							public ErrorHandlingConfigurationItem(Item innerItem) : base(innerItem) {}
public static implicit operator ErrorHandlingConfigurationItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ErrorHandlingConfigurationItem(innerItem) : null;
	}
public static implicit operator Item(ErrorHandlingConfigurationItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual LookupField _404PageLocation => InnerItem.Fields[FieldIds._404PageLocation];

						}
					}
				







// Thread.Foundation.ErrorHandling.Error_Handling_Configuration (/sitecore/templates/Foundation/Error Handling/Error Handling Configuration 8148e537-118d-4f13-b6e4-c70036c5b915)
	// _404_Page_Location (be5681b8-5cd7-429e-8676-dd9c73ea965c)
		// Type: Droptree
		// Section: Error Page Configuration
		// Sort Order: 100
		// Source: query:ancestor-or-self::*[@@name='Home']/*

