export default {
  pageTitle: {
    contentType: "",
    title: "Not a member yet? Sign up!",
    subtitle: "",
  },
  pageMeta: null,
  breadcrumbs: {
    items: ["Home", "Register"],
  },
  formData: {
    form: {
      formTitle: "",
      first: {
        autocomplete: "given-name",
        error: false,
        errorMsg: "First Name is required",
        label: "First Name",
        name: "fname",
        placeholder: "e.g. John",
        required: true,
        type: "text",
        validationType: "text",
      },
      last: {
        autocomplete: "family-name",
        error: false,
        errorMsg: "Last Name is required",
        label: "Last Name",
        name: "lname",
        placeholder: "e.g. Doe",
        required: true,
        type: "text",
        validationType: "text",
      },
      email: {
        autocomplete: "email",
        error: false,
        errorMsg: "Email Address is required",
        label: "Email Address",
        name: "email",
        placeholder: "your.name@example.com",
        required: true,
        type: "email",
        validationType: "email",
      },
      password: {
        autocomplete: "new-password",
        error: false,
        errorMsg: "Password is required",
        label: "Password",
        name: "password",
        placeholder: "6-20 characters (A-Z, a-z, 0-9)",
        required: true,
        type: "password",
        validationType: "password",
      },
      passwordMatch: {
        autocomplete: "new-password",
        error: false,
        errorMsg: "Passwords don't match",
        label: "Re-enter Password",
        name: "password-match",
        placeholder: "",
        required: true,
        type: "password",
        validationType: "passwordMatch",
      },
    },
  },
};
