
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace AtriusHealth.Foundation.Theme
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ColorItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("a3960764-19cc-4eb6-9b99-ff7b8e062dc2");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public ColorItem(Item innerItem) : base(innerItem) {}
public static implicit operator ColorItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ColorItem(innerItem) : null;
	}
public static implicit operator Item(ColorItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace AtriusHealth.Foundation.Theme
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ColorPairingItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("618a2809-d88a-4f41-9215-75d558121610");
							public static class FieldIds
		{

			public static readonly string BackgroundColor = "b7265fde-0fac-48d5-bed3-cca546fcc6bd";

			public static readonly string ForegroundColor = "9d35680b-d5b4-4977-8598-87437702a5e1";
}

							public ColorPairingItem(Item innerItem) : base(innerItem) {}
public static implicit operator ColorPairingItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ColorPairingItem(innerItem) : null;
	}
public static implicit operator Item(ColorPairingItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual LookupField BackgroundColor => InnerItem.Fields[FieldIds.BackgroundColor];

			public virtual LookupField ForegroundColor => InnerItem.Fields[FieldIds.ForegroundColor];

						}
					}
				

					namespace AtriusHealth.Foundation.Theme
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ColorPairingsFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("2491353e-0d76-4e19-a14f-03cc66def9a6");
							public static class FieldIds
		{
}

							public ColorPairingsFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator ColorPairingsFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ColorPairingsFolderItem(innerItem) : null;
	}
public static implicit operator Item(ColorPairingsFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace AtriusHealth.Foundation.Theme
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ColorsFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("a3c4ee02-c076-447c-b089-b3f7ce30a03c");
							public static class FieldIds
		{
}

							public ColorsFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator ColorsFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ColorsFolderItem(innerItem) : null;
	}
public static implicit operator Item(ColorsFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace AtriusHealth.Foundation.Theme
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ThemeItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("01258d88-4119-47a5-87f1-f83fc76c92a9");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public ThemeItem(Item innerItem) : base(innerItem) {}
public static implicit operator ThemeItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ThemeItem(innerItem) : null;
	}
public static implicit operator Item(ThemeItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace AtriusHealth.Foundation.Theme
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ThemeFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("33496225-ec24-4b81-a8d3-f4c60f8bad0c");
							public static class FieldIds
		{
}

							public ThemeFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator ThemeFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ThemeFolderItem(innerItem) : null;
	}
public static implicit operator Item(ThemeFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				





					namespace AtriusHealth.Foundation.Theme
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
						using Sitecore.Mvc.Presentation;
						using AtriusHealth.Foundation.Orm;

						public partial class ThemeRenderingParameters : AtriusHealthRenderingParameters
						{
							public static class Fields
		{

			public static string Theme = "Theme";
}

							public ThemeRenderingParameters() : base(string.Empty) {}
public ThemeRenderingParameters(string parametersAsQueryString) : base(parametersAsQueryString) {}

							
				public virtual AtriusHealth.Foundation.Theme.ThemeItem Theme => GetItemValue(Fields.Theme);

						}
					}
				



// AtriusHealth.Foundation.Theme.Color (/sitecore/templates/Foundation/Theme/Color a3960764-19cc-4eb6-9b99-ff7b8e062dc2)

// AtriusHealth.Foundation.Theme.Color_Pairing (/sitecore/templates/Foundation/Theme/Color Pairing 618a2809-d88a-4f41-9215-75d558121610)
	// Background_Color (b7265fde-0fac-48d5-bed3-cca546fcc6bd)
		// Type: Droplink
		// Section: Display Options
		// Sort Order: 100
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Configuration/Enumerations/Colors/*
	// Foreground_Color (9d35680b-d5b4-4977-8598-87437702a5e1)
		// Type: Droplink
		// Section: Display Options
		// Sort Order: 200
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Configuration/Enumerations/Colors/*

// AtriusHealth.Foundation.Theme.Color_Pairings_Folder (/sitecore/templates/Foundation/Theme/Color Pairings Folder 2491353e-0d76-4e19-a14f-03cc66def9a6)

// AtriusHealth.Foundation.Theme.Colors_Folder (/sitecore/templates/Foundation/Theme/Colors Folder a3c4ee02-c076-447c-b089-b3f7ce30a03c)

// AtriusHealth.Foundation.Theme.Theme (/sitecore/templates/Foundation/Theme/Theme 01258d88-4119-47a5-87f1-f83fc76c92a9)

// AtriusHealth.Foundation.Theme.Theme_Folder (/sitecore/templates/Foundation/Theme/Theme Folder 33496225-ec24-4b81-a8d3-f4c60f8bad0c)

// AtriusHealth.Foundation.Theme.Theme_Rendering_Parameters (/sitecore/templates/Foundation/Theme/Theme Rendering Parameters f96bbe64-fa1e-45b6-87f7-63c720ea7a3d)
	// Theme (5107ff88-ce34-4cbd-bf71-3d511c049fb0)
		// Type: custom=AtriusHealth.Foundation.Theme.ThemeItem
		// Section: Display Options
		// Sort Order: 200
		// Source: /sitecore/content/Global Configuration/Enumerations/Themes

