
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class EmailFrequencyItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("a580d907-62fa-4935-84c0-8d8591a7d0d4");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public EmailFrequencyItem(Item innerItem) : base(innerItem) {}
public static implicit operator EmailFrequencyItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new EmailFrequencyItem(innerItem) : null;
	}
public static implicit operator Item(EmailFrequencyItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class EmailFrequencyFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("af84df6a-b5ff-4b6a-996d-17eae16aec3f");
							public static class FieldIds
		{
}

							public EmailFrequencyFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator EmailFrequencyFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new EmailFrequencyFolderItem(innerItem) : null;
	}
public static implicit operator Item(EmailFrequencyFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class EmailListItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("77f33dcc-04ef-4c40-8f34-7a131576180e");
							public static class FieldIds
		{

			public static readonly string ShortDescription = "f4e5896d-004e-499d-b8f0-23345baef94d";

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public EmailListItem(Item innerItem) : base(innerItem) {}
public static implicit operator EmailListItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new EmailListItem(innerItem) : null;
	}
public static implicit operator Item(EmailListItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField ShortDescription => InnerItem.Fields[FieldIds.ShortDescription];

			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class EmailListFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("b4229f69-76dc-440c-8d4b-440309341aa1");
							public static class FieldIds
		{
}

							public EmailListFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator EmailListFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new EmailListFolderItem(innerItem) : null;
	}
public static implicit operator Item(EmailListFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class EnumerationsFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("474c209d-f0ce-49e7-8271-b7abc6ddf4df");
							public static class FieldIds
		{
}

							public EnumerationsFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator EnumerationsFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new EnumerationsFolderItem(innerItem) : null;
	}
public static implicit operator Item(EnumerationsFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class GenderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("e992befe-ac37-422a-9b9e-2696f5f00d87");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public GenderItem(Item innerItem) : base(innerItem) {}
public static implicit operator GenderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new GenderItem(innerItem) : null;
	}
public static implicit operator Item(GenderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class GendersFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("48e0cc49-1602-422f-8fc4-44814737591e");
							public static class FieldIds
		{
}

							public GendersFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator GendersFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new GendersFolderItem(innerItem) : null;
	}
public static implicit operator Item(GendersFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class NumberOfColumnsItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("03f0a1d9-afa6-48d1-8db1-9b2195733caf");
							public static class FieldIds
		{

			public static readonly string Value = "0dc82897-5b0f-47ce-87bd-6957ab817afa";
}

							public NumberOfColumnsItem(Item innerItem) : base(innerItem) {}
public static implicit operator NumberOfColumnsItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new NumberOfColumnsItem(innerItem) : null;
	}
public static implicit operator Item(NumberOfColumnsItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual Field Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class NumberOfColumnsFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("fbd8d65e-ea3b-413a-90de-93f7fedca0bc");
							public static class FieldIds
		{
}

							public NumberOfColumnsFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator NumberOfColumnsFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new NumberOfColumnsFolderItem(innerItem) : null;
	}
public static implicit operator Item(NumberOfColumnsFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class NumberOfItemsItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("aaad8d76-57dd-48ad-8601-8a573ed01709");
							public static class FieldIds
		{

			public static readonly string Value = "0dc82897-5b0f-47ce-87bd-6957ab817afa";
}

							public NumberOfItemsItem(Item innerItem) : base(innerItem) {}
public static implicit operator NumberOfItemsItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new NumberOfItemsItem(innerItem) : null;
	}
public static implicit operator Item(NumberOfItemsItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual Field Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class NumberOfItemsFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("f40da9da-33b5-4533-9cd0-ba0d000ccba6");
							public static class FieldIds
		{
}

							public NumberOfItemsFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator NumberOfItemsFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new NumberOfItemsFolderItem(innerItem) : null;
	}
public static implicit operator Item(NumberOfItemsFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class OrientationItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("2c81004c-2528-40e6-98c2-73f73138ab05");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public OrientationItem(Item innerItem) : base(innerItem) {}
public static implicit operator OrientationItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new OrientationItem(innerItem) : null;
	}
public static implicit operator Item(OrientationItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class OrientationsFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("400b3de1-9220-4cf9-a362-8023313c58cc");
							public static class FieldIds
		{
}

							public OrientationsFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator OrientationsFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new OrientationsFolderItem(innerItem) : null;
	}
public static implicit operator Item(OrientationsFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class RatioItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("415fdcdd-992d-4f3f-9752-e33fa61ca5db");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public RatioItem(Item innerItem) : base(innerItem) {}
public static implicit operator RatioItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new RatioItem(innerItem) : null;
	}
public static implicit operator Item(RatioItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class RatioFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("09f8503a-5ccf-4e2c-9a5c-d9cf0d73fd69");
							public static class FieldIds
		{
}

							public RatioFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator RatioFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new RatioFolderItem(innerItem) : null;
	}
public static implicit operator Item(RatioFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class SalutationItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("24b98cc6-fc73-4bc4-8b45-a40022047990");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public SalutationItem(Item innerItem) : base(innerItem) {}
public static implicit operator SalutationItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SalutationItem(innerItem) : null;
	}
public static implicit operator Item(SalutationItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class SalutationsFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("1625996d-32ba-4001-8d85-4072658a8bd0");
							public static class FieldIds
		{
}

							public SalutationsFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator SalutationsFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SalutationsFolderItem(innerItem) : null;
	}
public static implicit operator Item(SalutationsFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class StateItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("523c7870-f866-4f61-8e96-630405c2907f");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public StateItem(Item innerItem) : base(innerItem) {}
public static implicit operator StateItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new StateItem(innerItem) : null;
	}
public static implicit operator Item(StateItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class StatesFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("c7146fe4-a0a6-48fa-bdbd-9acc2723ff13");
							public static class FieldIds
		{
}

							public StatesFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator StatesFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new StatesFolderItem(innerItem) : null;
	}
public static implicit operator Item(StatesFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class SuffixItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("7a623f5c-692d-45ce-a749-0aa63f680a67");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public SuffixItem(Item innerItem) : base(innerItem) {}
public static implicit operator SuffixItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SuffixItem(innerItem) : null;
	}
public static implicit operator Item(SuffixItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class SuffixesFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("439b37c1-9ad8-4f12-bb2a-47b46eee254b");
							public static class FieldIds
		{
}

							public SuffixesFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator SuffixesFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SuffixesFolderItem(innerItem) : null;
	}
public static implicit operator Item(SuffixesFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class TextAlignmentItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("6eb8bc7f-e231-44ad-92b2-b1fbac97b3b1");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public TextAlignmentItem(Item innerItem) : base(innerItem) {}
public static implicit operator TextAlignmentItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new TextAlignmentItem(innerItem) : null;
	}
public static implicit operator Item(TextAlignmentItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class TextAlignmentFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("56c607e1-b07a-47e9-9041-04703acafd3c");
							public static class FieldIds
		{
}

							public TextAlignmentFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator TextAlignmentFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new TextAlignmentFolderItem(innerItem) : null;
	}
public static implicit operator Item(TextAlignmentFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _EnumerationBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("cabe55a1-4397-4b0a-a682-3578aef7e724");
							public static class FieldIds
		{

			public static readonly string Value = "197fd7ed-d7de-4445-a87d-3a6b9e845000";
}

							public _EnumerationBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _EnumerationBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _EnumerationBaseItem(innerItem) : null;
	}
public static implicit operator Item(_EnumerationBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				

					namespace Thread.Foundation.Enumerations
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _NumericalEnumerationBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("7d24dfac-bdf7-4bd2-a2e7-159e300c0170");
							public static class FieldIds
		{

			public static readonly string Value = "0dc82897-5b0f-47ce-87bd-6957ab817afa";
}

							public _NumericalEnumerationBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _NumericalEnumerationBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _NumericalEnumerationBaseItem(innerItem) : null;
	}
public static implicit operator Item(_NumericalEnumerationBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual Field Value => InnerItem.Fields[FieldIds.Value];

						}
					}
				







// Thread.Foundation.Enumerations.Email_Frequency (/sitecore/templates/Foundation/Enumerations/Email Frequency a580d907-62fa-4935-84c0-8d8591a7d0d4)

// Thread.Foundation.Enumerations.Email_Frequency_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Email Frequency Folder af84df6a-b5ff-4b6a-996d-17eae16aec3f)

// Thread.Foundation.Enumerations.Email_List (/sitecore/templates/Foundation/Enumerations/Email List 77f33dcc-04ef-4c40-8f34-7a131576180e)
	// Short_Description (f4e5896d-004e-499d-b8f0-23345baef94d)
		// Type: Single-Line Text
		// Section: Display Options
		// Sort Order: 100
		// Source: 

// Thread.Foundation.Enumerations.Email_List_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Email List Folder b4229f69-76dc-440c-8d4b-440309341aa1)

// Thread.Foundation.Enumerations.Enumerations_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Enumerations Folder 474c209d-f0ce-49e7-8271-b7abc6ddf4df)

// Thread.Foundation.Enumerations.Gender (/sitecore/templates/Foundation/Enumerations/Gender e992befe-ac37-422a-9b9e-2696f5f00d87)

// Thread.Foundation.Enumerations.Genders_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Genders Folder 48e0cc49-1602-422f-8fc4-44814737591e)

// Thread.Foundation.Enumerations.Number_Of_Columns (/sitecore/templates/Foundation/Enumerations/Number of Columns 03f0a1d9-afa6-48d1-8db1-9b2195733caf)

// Thread.Foundation.Enumerations.Number_Of_Columns_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Number of Columns Folder fbd8d65e-ea3b-413a-90de-93f7fedca0bc)

// Thread.Foundation.Enumerations.Number_Of_Items (/sitecore/templates/Foundation/Enumerations/Number of Items aaad8d76-57dd-48ad-8601-8a573ed01709)

// Thread.Foundation.Enumerations.Number_Of_Items_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Number of Items Folder f40da9da-33b5-4533-9cd0-ba0d000ccba6)

// Thread.Foundation.Enumerations.Orientation (/sitecore/templates/Foundation/Enumerations/Orientation 2c81004c-2528-40e6-98c2-73f73138ab05)

// Thread.Foundation.Enumerations.Orientations_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Orientations Folder 400b3de1-9220-4cf9-a362-8023313c58cc)

// Thread.Foundation.Enumerations.Ratio (/sitecore/templates/Foundation/Enumerations/Ratio 415fdcdd-992d-4f3f-9752-e33fa61ca5db)

// Thread.Foundation.Enumerations.Ratio_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Ratio Folder 09f8503a-5ccf-4e2c-9a5c-d9cf0d73fd69)

// Thread.Foundation.Enumerations.Salutation (/sitecore/templates/Foundation/Enumerations/Salutation 24b98cc6-fc73-4bc4-8b45-a40022047990)

// Thread.Foundation.Enumerations.Salutations_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Salutations Folder 1625996d-32ba-4001-8d85-4072658a8bd0)

// Thread.Foundation.Enumerations.State (/sitecore/templates/Foundation/Enumerations/State 523c7870-f866-4f61-8e96-630405c2907f)

// Thread.Foundation.Enumerations.States__Folder (/sitecore/templates/Foundation/Enumerations/Folders/States  Folder c7146fe4-a0a6-48fa-bdbd-9acc2723ff13)

// Thread.Foundation.Enumerations.Suffix (/sitecore/templates/Foundation/Enumerations/Suffix 7a623f5c-692d-45ce-a749-0aa63f680a67)

// Thread.Foundation.Enumerations.Suffixes__Folder (/sitecore/templates/Foundation/Enumerations/Folders/Suffixes  Folder 439b37c1-9ad8-4f12-bb2a-47b46eee254b)

// Thread.Foundation.Enumerations.Text_Alignment (/sitecore/templates/Foundation/Enumerations/Text Alignment 6eb8bc7f-e231-44ad-92b2-b1fbac97b3b1)

// Thread.Foundation.Enumerations.Text_Alignment_Folder (/sitecore/templates/Foundation/Enumerations/Folders/Text Alignment Folder 56c607e1-b07a-47e9-9041-04703acafd3c)

// Thread.Foundation.Enumerations._Enumeration_Base (/sitecore/templates/Foundation/Enumerations/_Enumeration Base cabe55a1-4397-4b0a-a682-3578aef7e724)
	// Value (197fd7ed-d7de-4445-a87d-3a6b9e845000)
		// Type: Single-Line Text
		// Section: Value
		// Sort Order: 100
		// Source: 

// Thread.Foundation.Enumerations._Numerical_Enumeration_Base (/sitecore/templates/Foundation/Enumerations/_Numerical Enumeration Base 7d24dfac-bdf7-4bd2-a2e7-159e300c0170)
	// Value (0dc82897-5b0f-47ce-87bd-6957ab817afa)
		// Type: Integer
		// Section: Value
		// Sort Order: 100
		// Source: 

