
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Feature.Events
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _EventDatesItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("b906556e-0ab9-4174-9520-26c282933569");
							public static class FieldIds
		{

			public static readonly string EndDate = "1fa41737-7a7b-484d-ae33-49be52a1af41";

			public static readonly string StartDate = "4037909f-26bb-42b7-9f37-7cd0b5e941bb";
}

							public _EventDatesItem(Item innerItem) : base(innerItem) {}
public static implicit operator _EventDatesItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _EventDatesItem(innerItem) : null;
	}
public static implicit operator Item(_EventDatesItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual DateField EndDate => InnerItem.Fields[FieldIds.EndDate];

			public virtual DateField StartDate => InnerItem.Fields[FieldIds.StartDate];

						}
					}
				

					namespace Thread.Feature.Events
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _EventDetailsItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("26b33d54-4f6b-4e86-b3f3-5d25a68c2941");
							public static class FieldIds
		{

			public static readonly string Address1 = "99f3f951-5ae8-4777-b705-354e7f9e4f9a";

			public static readonly string Address2 = "701473a3-bf78-46eb-b37d-d581fda816be";

			public static readonly string City = "6081c484-0ec5-4aac-bcfc-9d1a38b68900";

			public static readonly string RegistrationLink = "7fe91416-7d9a-491b-a738-1566d402bd4b";

			public static readonly string ShortDescription = "7cff50ee-ac60-4ab8-a0ca-d43df14bac2d";

			public static readonly string State = "750276e5-5ffa-4afe-9d5d-2db3a199c7e4";

			public static readonly string ZipCode = "6592df0a-5b31-402b-ba41-db4137d0e260";
}

							public _EventDetailsItem(Item innerItem) : base(innerItem) {}
public static implicit operator _EventDetailsItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _EventDetailsItem(innerItem) : null;
	}
public static implicit operator Item(_EventDetailsItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Address1 => InnerItem.Fields[FieldIds.Address1];

			public virtual TextField Address2 => InnerItem.Fields[FieldIds.Address2];

			public virtual TextField City => InnerItem.Fields[FieldIds.City];

			public virtual LinkField RegistrationLink => InnerItem.Fields[FieldIds.RegistrationLink];

			public virtual TextField ShortDescription => InnerItem.Fields[FieldIds.ShortDescription];

			public virtual LookupField State => InnerItem.Fields[FieldIds.State];

			public virtual TextField ZipCode => InnerItem.Fields[FieldIds.ZipCode];

						}
					}
				







// Thread.Feature.Events._Event_Dates (/sitecore/templates/Feature/Events/_Event Dates b906556e-0ab9-4174-9520-26c282933569)
	// End_Date (1fa41737-7a7b-484d-ae33-49be52a1af41)
		// Type: Datetime
		// Section: Date
		// Sort Order: 200
		// Source: 
	// Start_Date (4037909f-26bb-42b7-9f37-7cd0b5e941bb)
		// Type: Datetime
		// Section: Date
		// Sort Order: 100
		// Source: 

// Thread.Feature.Events._Event_Details (/sitecore/templates/Feature/Events/_Event Details 26b33d54-4f6b-4e86-b3f3-5d25a68c2941)
	// Address_1 (99f3f951-5ae8-4777-b705-354e7f9e4f9a)
		// Type: Single-Line Text
		// Section: Event Details
		// Sort Order: 100
		// Source: 
	// Address_2 (701473a3-bf78-46eb-b37d-d581fda816be)
		// Type: Single-Line Text
		// Section: Event Details
		// Sort Order: 200
		// Source: 
	// City (6081c484-0ec5-4aac-bcfc-9d1a38b68900)
		// Type: Single-Line Text
		// Section: Event Details
		// Sort Order: 300
		// Source: 
	// Registration_Link (7fe91416-7d9a-491b-a738-1566d402bd4b)
		// Type: General Link
		// Section: Event Details
		// Sort Order: 700
		// Source: 
	// Short_Description (7cff50ee-ac60-4ab8-a0ca-d43df14bac2d)
		// Type: Multi-Line Text
		// Section: Event Details
		// Sort Order: 600
		// Source: 
	// State (750276e5-5ffa-4afe-9d5d-2db3a199c7e4)
		// Type: Droplink
		// Section: Event Details
		// Sort Order: 400
		// Source: /sitecore/content/Global Configuration/Enumerations/States
	// Zip_Code (6592df0a-5b31-402b-ba41-db4137d0e260)
		// Type: Single-Line Text
		// Section: Event Details
		// Sort Order: 500
		// Source: 

