
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace AtriusHealth.Feature.Robots
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class RobotsConfigurationItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("cb803dab-1f25-469b-b5ff-5cea4ac39edd");
							public static class FieldIds
		{

			public static readonly string RobotsText = "81c63ec4-15aa-4280-8379-9a83ae14e4f2";
}

							public RobotsConfigurationItem(Item innerItem) : base(innerItem) {}
public static implicit operator RobotsConfigurationItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new RobotsConfigurationItem(innerItem) : null;
	}
public static implicit operator Item(RobotsConfigurationItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField RobotsText => InnerItem.Fields[FieldIds.RobotsText];

						}
					}
				







// AtriusHealth.Feature.Robots.Robots_Configuration (/sitecore/templates/Feature/Robots/Robots Configuration cb803dab-1f25-469b-b5ff-5cea4ac39edd)
	// Robots_Text (81c63ec4-15aa-4280-8379-9a83ae14e4f2)
		// Type: Multi-Line Text
		// Section: Robots Configuration
		// Sort Order: 100
		// Source: 

