
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace AtriusHealth.Foundation.Account
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _MemberAccountPageBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("03fbb497-88ef-4c34-8a55-195601431a6d");
							public static class FieldIds
		{
}

							public _MemberAccountPageBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _MemberAccountPageBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _MemberAccountPageBaseItem(innerItem) : null;
	}
public static implicit operator Item(_MemberAccountPageBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				







// AtriusHealth.Foundation.Account._Member_Account_Page_Base (/sitecore/templates/Foundation/Account/_Member Account Page Base 03fbb497-88ef-4c34-8a55-195601431a6d)

