
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Foundation.Workflow
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ScheduledPublishingWorkflowCommentsItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("2660c339-7e02-49c6-b9b7-e6b6e091e40f");
							public static class FieldIds
		{

			public static readonly string PublishDate = "88672ca5-5b66-48ab-8865-4d8c6cebda25";

			public static readonly string UnpublishDate = "76c1de22-e8d0-4c5a-a72c-081aa45a5220";
}

							public ScheduledPublishingWorkflowCommentsItem(Item innerItem) : base(innerItem) {}
public static implicit operator ScheduledPublishingWorkflowCommentsItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ScheduledPublishingWorkflowCommentsItem(innerItem) : null;
	}
public static implicit operator Item(ScheduledPublishingWorkflowCommentsItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual DateField PublishDate => InnerItem.Fields[FieldIds.PublishDate];

			public virtual DateField UnpublishDate => InnerItem.Fields[FieldIds.UnpublishDate];

						}
					}
				







// Thread.Foundation.Workflow.Scheduled_Publishing_Workflow_Comments (/sitecore/templates/Foundation/Workflow/Scheduled Publishing Workflow Comments 2660c339-7e02-49c6-b9b7-e6b6e091e40f)
	// Publish_Date (88672ca5-5b66-48ab-8865-4d8c6cebda25)
		// Type: Datetime
		// Section: Schedule
		// Sort Order: 100
		// Source: 
	// Unpublish_Date (76c1de22-e8d0-4c5a-a72c-081aa45a5220)
		// Type: Datetime
		// Section: Schedule
		// Sort Order: 200
		// Source: 

