
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Feature.Multimedia
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ImageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("1393e28b-2a66-428c-81f9-bbfe01650e48");
							public static class FieldIds
		{

			public static readonly string Image = "bc91a53d-f539-4275-b803-05286d41151a";

			public static readonly string Caption = "9444c804-b802-40b7-a41b-62e64f3fba78";

			public static readonly string Title = "91c417a4-6c8c-414f-a791-dea64dad2bba";
}

							public ImageItem(Item innerItem) : base(innerItem) {}
public static implicit operator ImageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ImageItem(innerItem) : null;
	}
public static implicit operator Item(ImageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual ImageField Image => InnerItem.Fields[FieldIds.Image];

			public virtual TextField Caption => InnerItem.Fields[FieldIds.Caption];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				

					namespace Thread.Feature.Multimedia
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ImageGridItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("ef23bbfe-e8e8-421b-8580-75b7d5f77c12");
							public static class FieldIds
		{

			public static readonly string Caption = "9444c804-b802-40b7-a41b-62e64f3fba78";

			public static readonly string Title = "91c417a4-6c8c-414f-a791-dea64dad2bba";
}

							public ImageGridItem(Item innerItem) : base(innerItem) {}
public static implicit operator ImageGridItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ImageGridItem(innerItem) : null;
	}
public static implicit operator Item(ImageGridItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Caption => InnerItem.Fields[FieldIds.Caption];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				

					namespace Thread.Feature.Multimedia
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class SlideshowItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("c7f38bce-98f1-4693-93f7-c678dc6d9bcd");
							public static class FieldIds
		{

			public static readonly string Title = "3c315287-123b-430f-9a5a-921807496b29";
}

							public SlideshowItem(Item innerItem) : base(innerItem) {}
public static implicit operator SlideshowItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SlideshowItem(innerItem) : null;
	}
public static implicit operator Item(SlideshowItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				

					namespace Thread.Feature.Multimedia
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class VideoItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("62057676-a2a9-4375-9f38-06005bb0bb10");
							public static class FieldIds
		{

			public static readonly string Image = "da7d7a99-87be-48ce-8943-0d41de09224e";

			public static readonly string Transcript = "1b4c029d-b923-4b52-b239-44dfd71a0cad";

			public static readonly string Video = "a8c37da0-9719-4af3-a22c-0aae7e96b029";

			public static readonly string Caption = "9444c804-b802-40b7-a41b-62e64f3fba78";

			public static readonly string Title = "91c417a4-6c8c-414f-a791-dea64dad2bba";
}

							public VideoItem(Item innerItem) : base(innerItem) {}
public static implicit operator VideoItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new VideoItem(innerItem) : null;
	}
public static implicit operator Item(VideoItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual ImageField Image => InnerItem.Fields[FieldIds.Image];

			public virtual FileField Transcript => InnerItem.Fields[FieldIds.Transcript];

			public virtual LinkField Video => InnerItem.Fields[FieldIds.Video];

			public virtual TextField Caption => InnerItem.Fields[FieldIds.Caption];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				

					namespace Thread.Feature.Multimedia
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _MultimediaBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("be629c54-8937-4711-87f7-edeebbf69096");
							public static class FieldIds
		{

			public static readonly string Caption = "9444c804-b802-40b7-a41b-62e64f3fba78";

			public static readonly string Title = "91c417a4-6c8c-414f-a791-dea64dad2bba";
}

							public _MultimediaBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _MultimediaBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _MultimediaBaseItem(innerItem) : null;
	}
public static implicit operator Item(_MultimediaBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Caption => InnerItem.Fields[FieldIds.Caption];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				





					namespace Thread.Feature.Multimedia
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
						using Sitecore.Mvc.Presentation;
						using Thread.Foundation.Orm;

						public partial class VideoParameters : ThreadRenderingParameters
						{
							public static class Fields
		{

			public static string DarkPlayIcon = "Dark Play Icon";
}

							public VideoParameters() : base(string.Empty) {}
public VideoParameters(string parametersAsQueryString) : base(parametersAsQueryString) {}

							
				public virtual bool DarkPlayIcon => GetBoolValue(Fields.DarkPlayIcon);

						}
					}
				



// Thread.Feature.Multimedia.Image (/sitecore/templates/Feature/Multimedia/Image 1393e28b-2a66-428c-81f9-bbfe01650e48)
	// Image (bc91a53d-f539-4275-b803-05286d41151a)
		// Type: Image
		// Section: Image
		// Sort Order: 100
		// Source: 

// Thread.Feature.Multimedia.Image_Grid (/sitecore/templates/Feature/Multimedia/Image Grid ef23bbfe-e8e8-421b-8580-75b7d5f77c12)

// Thread.Feature.Multimedia.Slideshow (/sitecore/templates/Feature/Multimedia/Slideshow c7f38bce-98f1-4693-93f7-c678dc6d9bcd)
	// Title (3c315287-123b-430f-9a5a-921807496b29)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

// Thread.Feature.Multimedia.Video (/sitecore/templates/Feature/Multimedia/Video 62057676-a2a9-4375-9f38-06005bb0bb10)
	// Image (da7d7a99-87be-48ce-8943-0d41de09224e)
		// Type: Image
		// Section: Image
		// Sort Order: 100
		// Source: 
	// Transcript (1b4c029d-b923-4b52-b239-44dfd71a0cad)
		// Type: File
		// Section: Text
		// Sort Order: 100
		// Source: 
	// Video (a8c37da0-9719-4af3-a22c-0aae7e96b029)
		// Type: General Link
		// Section: Video
		// Sort Order: 100
		// Source: 

// Thread.Feature.Multimedia.Video_Parameters (/sitecore/templates/Feature/Multimedia/Video Parameters 70293405-7cf1-4e46-9cb8-eefdcb77606f)
	// Dark_Play_Icon (785cc731-6eb8-45d6-aaa4-402151bc0944)
		// Type: Checkbox
		// Section: Display Options
		// Sort Order: 100
		// Source: 

// Thread.Feature.Multimedia._Multimedia_Base (/sitecore/templates/Feature/Multimedia/_Multimedia Base be629c54-8937-4711-87f7-edeebbf69096)
	// Caption (9444c804-b802-40b7-a41b-62e64f3fba78)
		// Type: Single-Line Text
		// Section: Text
		// Sort Order: 100
		// Source: 
	// Title (91c417a4-6c8c-414f-a791-dea64dad2bba)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

