
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace AtriusHealth.Foundation.Multisite
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class GlobalConfigurationFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("48f39ecb-369a-495e-9807-6010c6c69870");
							public static class FieldIds
		{
}

							public GlobalConfigurationFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator GlobalConfigurationFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new GlobalConfigurationFolderItem(innerItem) : null;
	}
public static implicit operator Item(GlobalConfigurationFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace AtriusHealth.Foundation.Multisite
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class SiteConfigurationFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("94dba5c9-8b1d-490c-8db3-dcb33f75ce9e");
							public static class FieldIds
		{
}

							public SiteConfigurationFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator SiteConfigurationFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SiteConfigurationFolderItem(innerItem) : null;
	}
public static implicit operator Item(SiteConfigurationFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace AtriusHealth.Foundation.Multisite
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class SiteFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("98ac8506-0017-4964-81a9-19b76fa9ee98");
							public static class FieldIds
		{
}

							public SiteFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator SiteFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SiteFolderItem(innerItem) : null;
	}
public static implicit operator Item(SiteFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				







// AtriusHealth.Foundation.Multisite.Global_Configuration_Folder (/sitecore/templates/Foundation/Multisite/Global Configuration Folder 48f39ecb-369a-495e-9807-6010c6c69870)

// AtriusHealth.Foundation.Multisite.Site_Configuration_Folder (/sitecore/templates/Foundation/Multisite/Site Configuration Folder 94dba5c9-8b1d-490c-8db3-dcb33f75ce9e)

// AtriusHealth.Foundation.Multisite.Site_Folder (/sitecore/templates/Foundation/Multisite/Site Folder 98ac8506-0017-4964-81a9-19b76fa9ee98)

