
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class DetailPageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("cc427b21-053a-4a29-ab94-1beae52b63f6");
							public static class FieldIds
		{

			public static readonly string DisplayDate = "3927b1aa-347c-4d88-9b93-b327eae1b6d0";

			public static readonly string Image16x9 = "f0e8ca34-1117-486d-88a8-ff0ab471e9c4";

			public static readonly string Image1x1 = "89f4ee5e-3e89-4e75-816b-5049d563b287";

			public static readonly string NoFollow = "1bd0fef8-5ee5-435b-bde3-a332a0709e8e";

			public static readonly string NoIndex = "497a98de-d47a-4da9-931e-100fc84d5ab1";

			public static readonly string SuppressInNavigation = "1ccdab5f-8819-4a04-a09a-4f66dfb65d12";

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string ContentType = "d7b9c27c-79e3-42a7-9b46-bff652ef0981";

			public static readonly string Topics = "027f5e1e-d0e5-4afd-9b7a-90a563504d47";

			public static readonly string Locations = "7928f523-5727-4843-ba3d-60874d4e6f6b";

			public static readonly string People = "bef10252-ea97-4433-a7e3-d924796e3950";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public DetailPageItem(Item innerItem) : base(innerItem) {}
public static implicit operator DetailPageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new DetailPageItem(innerItem) : null;
	}
public static implicit operator Item(DetailPageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual DateField DisplayDate => InnerItem.Fields[FieldIds.DisplayDate];

			public virtual ImageField Image16x9 => InnerItem.Fields[FieldIds.Image16x9];

			public virtual ImageField Image1x1 => InnerItem.Fields[FieldIds.Image1x1];

			public virtual CheckboxField NoFollow => InnerItem.Fields[FieldIds.NoFollow];

			public virtual CheckboxField NoIndex => InnerItem.Fields[FieldIds.NoIndex];

			public virtual CheckboxField SuppressInNavigation => InnerItem.Fields[FieldIds.SuppressInNavigation];

			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual LookupField ContentType => InnerItem.Fields[FieldIds.ContentType];

			public virtual MultilistField Topics => InnerItem.Fields[FieldIds.Topics];

			public virtual MultilistField Locations => InnerItem.Fields[FieldIds.Locations];

			public virtual MultilistField People => InnerItem.Fields[FieldIds.People];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class EventDetailPageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("530ae3aa-efbc-4658-9fd0-500b35919b0c");
							public static class FieldIds
		{

			public static readonly string Image16x9 = "f0e8ca34-1117-486d-88a8-ff0ab471e9c4";

			public static readonly string Image1x1 = "89f4ee5e-3e89-4e75-816b-5049d563b287";

			public static readonly string NoFollow = "1bd0fef8-5ee5-435b-bde3-a332a0709e8e";

			public static readonly string NoIndex = "497a98de-d47a-4da9-931e-100fc84d5ab1";

			public static readonly string SuppressInNavigation = "1ccdab5f-8819-4a04-a09a-4f66dfb65d12";

			public static readonly string EndDate = "1fa41737-7a7b-484d-ae33-49be52a1af41";

			public static readonly string StartDate = "4037909f-26bb-42b7-9f37-7cd0b5e941bb";

			public static readonly string Address1 = "99f3f951-5ae8-4777-b705-354e7f9e4f9a";

			public static readonly string Address2 = "701473a3-bf78-46eb-b37d-d581fda816be";

			public static readonly string City = "6081c484-0ec5-4aac-bcfc-9d1a38b68900";

			public static readonly string RegistrationLink = "7fe91416-7d9a-491b-a738-1566d402bd4b";

			public static readonly string ShortDescription = "7cff50ee-ac60-4ab8-a0ca-d43df14bac2d";

			public static readonly string State = "750276e5-5ffa-4afe-9d5d-2db3a199c7e4";

			public static readonly string ZipCode = "6592df0a-5b31-402b-ba41-db4137d0e260";

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string ContentType = "d7b9c27c-79e3-42a7-9b46-bff652ef0981";

			public static readonly string Topics = "027f5e1e-d0e5-4afd-9b7a-90a563504d47";

			public static readonly string Locations = "7928f523-5727-4843-ba3d-60874d4e6f6b";

			public static readonly string People = "bef10252-ea97-4433-a7e3-d924796e3950";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public EventDetailPageItem(Item innerItem) : base(innerItem) {}
public static implicit operator EventDetailPageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new EventDetailPageItem(innerItem) : null;
	}
public static implicit operator Item(EventDetailPageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual ImageField Image16x9 => InnerItem.Fields[FieldIds.Image16x9];

			public virtual ImageField Image1x1 => InnerItem.Fields[FieldIds.Image1x1];

			public virtual CheckboxField NoFollow => InnerItem.Fields[FieldIds.NoFollow];

			public virtual CheckboxField NoIndex => InnerItem.Fields[FieldIds.NoIndex];

			public virtual CheckboxField SuppressInNavigation => InnerItem.Fields[FieldIds.SuppressInNavigation];

			public virtual DateField EndDate => InnerItem.Fields[FieldIds.EndDate];

			public virtual DateField StartDate => InnerItem.Fields[FieldIds.StartDate];

			public virtual TextField Address1 => InnerItem.Fields[FieldIds.Address1];

			public virtual TextField Address2 => InnerItem.Fields[FieldIds.Address2];

			public virtual TextField City => InnerItem.Fields[FieldIds.City];

			public virtual LinkField RegistrationLink => InnerItem.Fields[FieldIds.RegistrationLink];

			public virtual TextField ShortDescription => InnerItem.Fields[FieldIds.ShortDescription];

			public virtual LookupField State => InnerItem.Fields[FieldIds.State];

			public virtual TextField ZipCode => InnerItem.Fields[FieldIds.ZipCode];

			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual LookupField ContentType => InnerItem.Fields[FieldIds.ContentType];

			public virtual MultilistField Topics => InnerItem.Fields[FieldIds.Topics];

			public virtual MultilistField Locations => InnerItem.Fields[FieldIds.Locations];

			public virtual MultilistField People => InnerItem.Fields[FieldIds.People];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class EventDetailPageFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("d2484ff3-61f6-4f4f-86e3-1194905040ea");
							public static class FieldIds
		{
}

							public EventDetailPageFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator EventDetailPageFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new EventDetailPageFolderItem(innerItem) : null;
	}
public static implicit operator Item(EventDetailPageFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class FormPageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("5153aaaf-55d0-4196-8392-c2a437763d43");
							public static class FieldIds
		{

			public static readonly string SuppressInNavigation = "1ccdab5f-8819-4a04-a09a-4f66dfb65d12";

			public static readonly string NoFollow = "1bd0fef8-5ee5-435b-bde3-a332a0709e8e";

			public static readonly string NoIndex = "497a98de-d47a-4da9-931e-100fc84d5ab1";

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public FormPageItem(Item innerItem) : base(innerItem) {}
public static implicit operator FormPageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new FormPageItem(innerItem) : null;
	}
public static implicit operator Item(FormPageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual CheckboxField SuppressInNavigation => InnerItem.Fields[FieldIds.SuppressInNavigation];

			public virtual CheckboxField NoFollow => InnerItem.Fields[FieldIds.NoFollow];

			public virtual CheckboxField NoIndex => InnerItem.Fields[FieldIds.NoIndex];

			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class HomepageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("82ea81b7-7358-405d-b8bb-8feaafc4835f");
							public static class FieldIds
		{

			public static readonly string MetaHtml = "f7504c40-7c68-42c2-be36-8bb61072f21b";

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public HomepageItem(Item innerItem) : base(innerItem) {}
public static implicit operator HomepageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new HomepageItem(innerItem) : null;
	}
public static implicit operator Item(HomepageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField MetaHtml => InnerItem.Fields[FieldIds.MetaHtml];

			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class LandingPageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("d358c2c1-0081-43bf-8f81-3c5ad05ed0ff");
							public static class FieldIds
		{

			public static readonly string Image16x9 = "f0e8ca34-1117-486d-88a8-ff0ab471e9c4";

			public static readonly string Image1x1 = "89f4ee5e-3e89-4e75-816b-5049d563b287";

			public static readonly string NoFollow = "1bd0fef8-5ee5-435b-bde3-a332a0709e8e";

			public static readonly string NoIndex = "497a98de-d47a-4da9-931e-100fc84d5ab1";

			public static readonly string SuppressInNavigation = "1ccdab5f-8819-4a04-a09a-4f66dfb65d12";

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string ContentType = "d7b9c27c-79e3-42a7-9b46-bff652ef0981";

			public static readonly string Topics = "027f5e1e-d0e5-4afd-9b7a-90a563504d47";

			public static readonly string Locations = "7928f523-5727-4843-ba3d-60874d4e6f6b";

			public static readonly string People = "bef10252-ea97-4433-a7e3-d924796e3950";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public LandingPageItem(Item innerItem) : base(innerItem) {}
public static implicit operator LandingPageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new LandingPageItem(innerItem) : null;
	}
public static implicit operator Item(LandingPageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual ImageField Image16x9 => InnerItem.Fields[FieldIds.Image16x9];

			public virtual ImageField Image1x1 => InnerItem.Fields[FieldIds.Image1x1];

			public virtual CheckboxField NoFollow => InnerItem.Fields[FieldIds.NoFollow];

			public virtual CheckboxField NoIndex => InnerItem.Fields[FieldIds.NoIndex];

			public virtual CheckboxField SuppressInNavigation => InnerItem.Fields[FieldIds.SuppressInNavigation];

			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual LookupField ContentType => InnerItem.Fields[FieldIds.ContentType];

			public virtual MultilistField Topics => InnerItem.Fields[FieldIds.Topics];

			public virtual MultilistField Locations => InnerItem.Fields[FieldIds.Locations];

			public virtual MultilistField People => InnerItem.Fields[FieldIds.People];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class LongFormPageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("99e330f6-238c-461a-a17f-94279cb87e9f");
							public static class FieldIds
		{

			public static readonly string DisplayDate = "3927b1aa-347c-4d88-9b93-b327eae1b6d0";

			public static readonly string Image16x9 = "f0e8ca34-1117-486d-88a8-ff0ab471e9c4";

			public static readonly string Image1x1 = "89f4ee5e-3e89-4e75-816b-5049d563b287";

			public static readonly string NoFollow = "1bd0fef8-5ee5-435b-bde3-a332a0709e8e";

			public static readonly string NoIndex = "497a98de-d47a-4da9-931e-100fc84d5ab1";

			public static readonly string SuppressInNavigation = "1ccdab5f-8819-4a04-a09a-4f66dfb65d12";

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string ContentType = "d7b9c27c-79e3-42a7-9b46-bff652ef0981";

			public static readonly string Topics = "027f5e1e-d0e5-4afd-9b7a-90a563504d47";

			public static readonly string Locations = "7928f523-5727-4843-ba3d-60874d4e6f6b";

			public static readonly string People = "bef10252-ea97-4433-a7e3-d924796e3950";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public LongFormPageItem(Item innerItem) : base(innerItem) {}
public static implicit operator LongFormPageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new LongFormPageItem(innerItem) : null;
	}
public static implicit operator Item(LongFormPageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual DateField DisplayDate => InnerItem.Fields[FieldIds.DisplayDate];

			public virtual ImageField Image16x9 => InnerItem.Fields[FieldIds.Image16x9];

			public virtual ImageField Image1x1 => InnerItem.Fields[FieldIds.Image1x1];

			public virtual CheckboxField NoFollow => InnerItem.Fields[FieldIds.NoFollow];

			public virtual CheckboxField NoIndex => InnerItem.Fields[FieldIds.NoIndex];

			public virtual CheckboxField SuppressInNavigation => InnerItem.Fields[FieldIds.SuppressInNavigation];

			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual LookupField ContentType => InnerItem.Fields[FieldIds.ContentType];

			public virtual MultilistField Topics => InnerItem.Fields[FieldIds.Topics];

			public virtual MultilistField Locations => InnerItem.Fields[FieldIds.Locations];

			public virtual MultilistField People => InnerItem.Fields[FieldIds.People];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class MemberAccountPageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("0b1d60f7-519f-4377-a13c-2cb025c89ce3");
							public static class FieldIds
		{

			public static readonly string SuppressInNavigation = "1ccdab5f-8819-4a04-a09a-4f66dfb65d12";

			public static readonly string NoFollow = "1bd0fef8-5ee5-435b-bde3-a332a0709e8e";

			public static readonly string NoIndex = "497a98de-d47a-4da9-931e-100fc84d5ab1";

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public MemberAccountPageItem(Item innerItem) : base(innerItem) {}
public static implicit operator MemberAccountPageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new MemberAccountPageItem(innerItem) : null;
	}
public static implicit operator Item(MemberAccountPageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual CheckboxField SuppressInNavigation => InnerItem.Fields[FieldIds.SuppressInNavigation];

			public virtual CheckboxField NoFollow => InnerItem.Fields[FieldIds.NoFollow];

			public virtual CheckboxField NoIndex => InnerItem.Fields[FieldIds.NoIndex];

			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class MultiPromoContainerItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("66dd30b1-acdb-4562-9041-b6b186237958");
							public static class FieldIds
		{
}

							public MultiPromoContainerItem(Item innerItem) : base(innerItem) {}
public static implicit operator MultiPromoContainerItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new MultiPromoContainerItem(innerItem) : null;
	}
public static implicit operator Item(MultiPromoContainerItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class PageFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("00241bde-5e47-462c-b1ee-f0e06ab28919");
							public static class FieldIds
		{
}

							public PageFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator PageFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new PageFolderItem(innerItem) : null;
	}
public static implicit operator Item(PageFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace Thread.Project.Demo
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class SearchPageItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("420a6589-0c9b-4d12-a6d3-0ee444dbfc98");
							public static class FieldIds
		{

			public static readonly string NoFollow = "1bd0fef8-5ee5-435b-bde3-a332a0709e8e";

			public static readonly string NoIndex = "497a98de-d47a-4da9-931e-100fc84d5ab1";

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public SearchPageItem(Item innerItem) : base(innerItem) {}
public static implicit operator SearchPageItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SearchPageItem(innerItem) : null;
	}
public static implicit operator Item(SearchPageItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual CheckboxField NoFollow => InnerItem.Fields[FieldIds.NoFollow];

			public virtual CheckboxField NoIndex => InnerItem.Fields[FieldIds.NoIndex];

			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				







// Thread.Project.Demo.Detail_Page (/sitecore/templates/Project/Demo/Pages/Detail Page cc427b21-053a-4a29-ab94-1beae52b63f6)

// Thread.Project.Demo.Event_Detail_Page (/sitecore/templates/Project/Demo/Pages/Event Detail Page 530ae3aa-efbc-4658-9fd0-500b35919b0c)

// Thread.Project.Demo.Event_Detail_Page_Folder (/sitecore/templates/Project/Demo/Folders/Event Detail Page Folder d2484ff3-61f6-4f4f-86e3-1194905040ea)

// Thread.Project.Demo.Form_Page (/sitecore/templates/Project/Demo/Pages/Form Page 5153aaaf-55d0-4196-8392-c2a437763d43)

// Thread.Project.Demo.Homepage (/sitecore/templates/Project/Demo/Pages/Homepage 82ea81b7-7358-405d-b8bb-8feaafc4835f)

// Thread.Project.Demo.Landing_Page (/sitecore/templates/Project/Demo/Pages/Landing Page d358c2c1-0081-43bf-8f81-3c5ad05ed0ff)

// Thread.Project.Demo.Long_Form_Page (/sitecore/templates/Project/Demo/Pages/Long Form Page 99e330f6-238c-461a-a17f-94279cb87e9f)

// Thread.Project.Demo.Member_Account_Page (/sitecore/templates/Project/Demo/Pages/Member Account Page 0b1d60f7-519f-4377-a13c-2cb025c89ce3)

// Thread.Project.Demo.Multi_Promo_Container (/sitecore/templates/Project/Demo/Promo/Multi Promo Container 66dd30b1-acdb-4562-9041-b6b186237958)

// Thread.Project.Demo.Page_Folder (/sitecore/templates/Project/Demo/Folders/Page Folder 00241bde-5e47-462c-b1ee-f0e06ab28919)

// Thread.Project.Demo.Search_Page (/sitecore/templates/Project/Demo/Pages/Search Page 420a6589-0c9b-4d12-a6d3-0ee444dbfc98)

