
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class RelatedLinkItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("a7d32dbf-149d-46a2-9024-4829aca2c2c0");
							public static class FieldIds
		{

			public static readonly string Link = "025827d7-badd-4a21-950f-b99c801e238e";
}

							public RelatedLinkItem(Item innerItem) : base(innerItem) {}
public static implicit operator RelatedLinkItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new RelatedLinkItem(innerItem) : null;
	}
public static implicit operator Item(RelatedLinkItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual LinkField Link => InnerItem.Fields[FieldIds.Link];

						}
					}
				

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class RelatedLinksItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("c6d29340-1d4c-40b3-9d8b-e18992b5e173");
							public static class FieldIds
		{

			public static readonly string RelatedLinks = "9f5610c3-5e8d-440a-b068-085038b9b05b";

			public static readonly string Title = "bb76ed58-6443-44db-a849-97d555ae241b";
}

							public RelatedLinksItem(Item innerItem) : base(innerItem) {}
public static implicit operator RelatedLinksItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new RelatedLinksItem(innerItem) : null;
	}
public static implicit operator Item(RelatedLinksItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual MultilistField RelatedLinks => InnerItem.Fields[FieldIds.RelatedLinks];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _DateBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("0068beae-cb7c-44ee-a5cb-db6e4668d383");
							public static class FieldIds
		{

			public static readonly string DisplayDate = "3927b1aa-347c-4d88-9b93-b327eae1b6d0";
}

							public _DateBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _DateBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _DateBaseItem(innerItem) : null;
	}
public static implicit operator Item(_DateBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual DateField DisplayDate => InnerItem.Fields[FieldIds.DisplayDate];

						}
					}
				

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _HeaderTitleBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("12cc6a13-24e7-418e-a610-8e56d718823c");
							public static class FieldIds
		{

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";
}

							public _HeaderTitleBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _HeaderTitleBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _HeaderTitleBaseItem(innerItem) : null;
	}
public static implicit operator Item(_HeaderTitleBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

						}
					}
				

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _ImageBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("f8bbfc46-ace9-4ddf-ae0f-c4120acf8db3");
							public static class FieldIds
		{

			public static readonly string Image16x9 = "f0e8ca34-1117-486d-88a8-ff0ab471e9c4";

			public static readonly string Image1x1 = "89f4ee5e-3e89-4e75-816b-5049d563b287";
}

							public _ImageBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _ImageBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _ImageBaseItem(innerItem) : null;
	}
public static implicit operator Item(_ImageBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual ImageField Image16x9 => InnerItem.Fields[FieldIds.Image16x9];

			public virtual ImageField Image1x1 => InnerItem.Fields[FieldIds.Image1x1];

						}
					}
				

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _ShortTitleBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("68f0c8d8-72fb-4837-a723-560c6373406b");
							public static class FieldIds
		{

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";
}

							public _ShortTitleBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _ShortTitleBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _ShortTitleBaseItem(innerItem) : null;
	}
public static implicit operator Item(_ShortTitleBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

						}
					}
				

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _SubtitleBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("82fa5927-bc57-45c7-bc0f-89984f4da43c");
							public static class FieldIds
		{

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public _SubtitleBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _SubtitleBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _SubtitleBaseItem(innerItem) : null;
	}
public static implicit operator Item(_SubtitleBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _SummaryBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("25f21d17-ea40-41bf-bcf8-a45a85808067");
							public static class FieldIds
		{

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";
}

							public _SummaryBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _SummaryBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _SummaryBaseItem(innerItem) : null;
	}
public static implicit operator Item(_SummaryBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

						}
					}
				

					namespace AtriusHealth.Feature.PageContent
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _TitleBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("97d4fb50-24eb-447c-9776-511475261822");
							public static class FieldIds
		{

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";
}

							public _TitleBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _TitleBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _TitleBaseItem(innerItem) : null;
	}
public static implicit operator Item(_TitleBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				







// AtriusHealth.Feature.PageContent.Related_Link (/sitecore/templates/Feature/Page Content/Related Link a7d32dbf-149d-46a2-9024-4829aca2c2c0)
	// Link (025827d7-badd-4a21-950f-b99c801e238e)
		// Type: General Link
		// Section: Link
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.PageContent.Related_Links (/sitecore/templates/Feature/Page Content/Related Links c6d29340-1d4c-40b3-9d8b-e18992b5e173)
	// Related_Links (9f5610c3-5e8d-440a-b068-085038b9b05b)
		// Type: Multilist with Search
		// Section: Links
		// Sort Order: 100
		// Source: StartSearchLocation=query:ancestor-or-self::*[@@templateid->'{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Home/Shared Components/Resource Links&Filter=+_templatename:Related Link
	// Title (bb76ed58-6443-44db-a849-97d555ae241b)
		// Type: Single-Line Text
		// Section: Text
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.PageContent._Date_Base (/sitecore/templates/Feature/Page Content/_Date Base 0068beae-cb7c-44ee-a5cb-db6e4668d383)
	// Display_Date (3927b1aa-347c-4d88-9b93-b327eae1b6d0)
		// Type: Date
		// Section: Date
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.PageContent._Header_Title_Base (/sitecore/templates/Feature/Page Content/_Header Title Base 12cc6a13-24e7-418e-a610-8e56d718823c)
	// Header_Title (d64a69f6-1317-47a1-a78b-2e22423c8133)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.PageContent._Image_Base (/sitecore/templates/Feature/Page Content/_Image Base f8bbfc46-ace9-4ddf-ae0f-c4120acf8db3)
	// Image_16x9 (f0e8ca34-1117-486d-88a8-ff0ab471e9c4)
		// Type: Image
		// Section: Image
		// Sort Order: 100
		// Source: 
	// Image_1x1 (89f4ee5e-3e89-4e75-816b-5049d563b287)
		// Type: Image
		// Section: Image
		// Sort Order: 200
		// Source: 

// AtriusHealth.Feature.PageContent._Short_Title_Base (/sitecore/templates/Feature/Page Content/_Short Title Base 68f0c8d8-72fb-4837-a723-560c6373406b)
	// Short_Title (10e9213f-9aad-4979-a6a4-912a36275bb9)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.PageContent._Subtitle_Base (/sitecore/templates/Feature/Page Content/_Subtitle Base 82fa5927-bc57-45c7-bc0f-89984f4da43c)
	// Subtitle (cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.PageContent._Summary_Base (/sitecore/templates/Feature/Page Content/_Summary Base 25f21d17-ea40-41bf-bcf8-a45a85808067)
	// Summary (19d48702-b149-4a2d-b72d-e3e8b5cf3bcc)
		// Type: Multi-Line Text
		// Section: Text
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.PageContent._Title_Base (/sitecore/templates/Feature/Page Content/_Title Base 97d4fb50-24eb-447c-9776-511475261822)
	// Title (91573f05-edb0-43cf-ac81-a6ca06c7fc0d)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

