---
ID: "db366b51-4df9-4907-a22e-3252bab798cb"
Parent: "162e04a6-74e0-4b1e-929b-9f1598e6b343"
Template: "c3b037a0-46e5-4b67-ac7a-a144b962a56f"
Path: /sitecore/layout/Placeholder Settings/Project/AtriusHealth/Member Account Page/Base
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161110T145057Z
