
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Feature.Banners
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class HeroItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("f76633f7-ec75-40b3-832b-ac997c6ecb22");
							public static class FieldIds
		{

			public static readonly string Image = "b96ca82b-a50a-4fc6-8830-ffda49603cd1";

			public static readonly string Link = "af81dce3-b8f9-46b1-9e28-83abe860ab8b";

			public static readonly string Subtitle = "a75149a6-1164-473c-b8c1-686639718bc1";

			public static readonly string Title = "201fa277-4f3c-4c28-beae-27f0ba548f1e";

			public static readonly string Video = "7d38a843-6009-46e1-abe2-508bdd504b3e";
}

							public HeroItem(Item innerItem) : base(innerItem) {}
public static implicit operator HeroItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new HeroItem(innerItem) : null;
	}
public static implicit operator Item(HeroItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual ImageField Image => InnerItem.Fields[FieldIds.Image];

			public virtual LinkField Link => InnerItem.Fields[FieldIds.Link];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual FileField Video => InnerItem.Fields[FieldIds.Video];

						}
					}
				

					namespace Thread.Feature.Banners
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class PageBannerItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("60ac7f1a-2dda-4022-8f6c-a75fd3732303");
							public static class FieldIds
		{

			public static readonly string Image = "8f6bb17a-0d9a-4fb5-b9de-1133ca7cfcd0";

			public static readonly string Video = "71733614-267d-4988-a80f-318a53c685a1";
}

							public PageBannerItem(Item innerItem) : base(innerItem) {}
public static implicit operator PageBannerItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new PageBannerItem(innerItem) : null;
	}
public static implicit operator Item(PageBannerItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual ImageField Image => InnerItem.Fields[FieldIds.Image];

			public virtual FileField Video => InnerItem.Fields[FieldIds.Video];

						}
					}
				

					namespace Thread.Feature.Banners
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class TextBannerItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("4e8757b1-b9a1-483b-a705-621f86420d75");
							public static class FieldIds
		{

			public static readonly string Link = "b457e6ab-c2b1-4e96-84c1-abb2c9f1ed4e";

			public static readonly string Subtitle = "fe18eb8b-d9bc-4255-a991-51a45a1ed655";

			public static readonly string Title = "6bb99ee9-359e-43cb-a9e9-9c199f8d318b";
}

							public TextBannerItem(Item innerItem) : base(innerItem) {}
public static implicit operator TextBannerItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new TextBannerItem(innerItem) : null;
	}
public static implicit operator Item(TextBannerItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual LinkField Link => InnerItem.Fields[FieldIds.Link];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				

					namespace Thread.Feature.Banners
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _PrivacyConfigurationItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("5e0e7757-c81c-4ddb-9b57-894e09d73619");
							public static class FieldIds
		{

			public static readonly string PrivacyDisclaimer = "01ee3336-a06d-420c-a27c-f09ebb1e1565";
}

							public _PrivacyConfigurationItem(Item innerItem) : base(innerItem) {}
public static implicit operator _PrivacyConfigurationItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _PrivacyConfigurationItem(innerItem) : null;
	}
public static implicit operator Item(_PrivacyConfigurationItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField PrivacyDisclaimer => InnerItem.Fields[FieldIds.PrivacyDisclaimer];

						}
					}
				





					namespace Thread.Feature.Banners
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
						using Sitecore.Mvc.Presentation;
						using Thread.Foundation.Orm;

						public partial class BannerParameters : ThreadRenderingParameters
						{
							public static class Fields
		{

			public static string BannerHeight = "Banner Height";

			public static string Opacity = "Opacity";

			public static string Theme = "Theme";
}

							public BannerParameters() : base(string.Empty) {}
public BannerParameters(string parametersAsQueryString) : base(parametersAsQueryString) {}

							
				public virtual int BannerHeight => GetIntValue(Fields.BannerHeight);

				public virtual float Opacity => GetFloatValue(Fields.Opacity);

				public virtual Thread.Foundation.Theme.ThemeItem Theme => GetItemValue(Fields.Theme);

						}
					}
				

					namespace Thread.Feature.Banners
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
						using Sitecore.Mvc.Presentation;
						using Thread.Foundation.Orm;

						public partial class TextBannerParameters : ThreadRenderingParameters
						{
							public static class Fields
		{

			public static string ExcludeTopMargin = "Exclude Top Margin";

			public static string Theme = "Theme";
}

							public TextBannerParameters() : base(string.Empty) {}
public TextBannerParameters(string parametersAsQueryString) : base(parametersAsQueryString) {}

							
				public virtual bool ExcludeTopMargin => GetBoolValue(Fields.ExcludeTopMargin);

				public virtual Thread.Foundation.Theme.ThemeItem Theme => GetItemValue(Fields.Theme);

						}
					}
				



// Thread.Feature.Banners.Banner_Parameters (/sitecore/templates/Feature/Banners/Banner Parameters 52d2d679-2816-4a79-afe8-ebd5f5e9a1e3)
	// Banner_Height (e0c93ebb-51c4-4e1f-b42f-2e1ff4c80a8b)
		// Type: Integer
		// Section: Display Options
		// Sort Order: 50
		// Source: 
	// Opacity (f8852b05-c2c5-4fa0-a102-2f2490102f11)
		// Type: Number
		// Section: Display Options
		// Sort Order: 100
		// Source: 

// Thread.Feature.Banners.Hero (/sitecore/templates/Feature/Banners/Hero f76633f7-ec75-40b3-832b-ac997c6ecb22)
	// Image (b96ca82b-a50a-4fc6-8830-ffda49603cd1)
		// Type: Image
		// Section: Image
		// Sort Order: 100
		// Source: 
	// Link (af81dce3-b8f9-46b1-9e28-83abe860ab8b)
		// Type: General Link
		// Section: Link
		// Sort Order: 400
		// Source: 
	// Subtitle (a75149a6-1164-473c-b8c1-686639718bc1)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 300
		// Source: 
	// Title (201fa277-4f3c-4c28-beae-27f0ba548f1e)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 200
		// Source: 
	// Video (7d38a843-6009-46e1-abe2-508bdd504b3e)
		// Type: File
		// Section: Video
		// Sort Order: 100
		// Source: 

// Thread.Feature.Banners.Page_Banner (/sitecore/templates/Feature/Banners/Page Banner 60ac7f1a-2dda-4022-8f6c-a75fd3732303)
	// Image (8f6bb17a-0d9a-4fb5-b9de-1133ca7cfcd0)
		// Type: Image
		// Section: Image
		// Sort Order: 100
		// Source: 
	// Video (71733614-267d-4988-a80f-318a53c685a1)
		// Type: File
		// Section: Video
		// Sort Order: 100
		// Source: 

// Thread.Feature.Banners.Text_Banner (/sitecore/templates/Feature/Banners/Text Banner 4e8757b1-b9a1-483b-a705-621f86420d75)
	// Link (b457e6ab-c2b1-4e96-84c1-abb2c9f1ed4e)
		// Type: General Link
		// Section: Link
		// Sort Order: 100
		// Source: 
	// Subtitle (fe18eb8b-d9bc-4255-a991-51a45a1ed655)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 200
		// Source: 
	// Title (6bb99ee9-359e-43cb-a9e9-9c199f8d318b)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

// Thread.Feature.Banners.Text_Banner_Parameters (/sitecore/templates/Feature/Banners/Text Banner Parameters 26713e59-27da-4b8b-bb29-e20f43e844f9)
	// Exclude_Top_Margin (62f206fd-06a3-4f06-99be-576e655ad640)
		// Type: Checkbox
		// Section: Display Options
		// Sort Order: 100
		// Source: 

// Thread.Feature.Banners._Privacy_Configuration (/sitecore/templates/Feature/Banners/_Privacy Configuration 5e0e7757-c81c-4ddb-9b57-894e09d73619)
	// Privacy_Disclaimer (01ee3336-a06d-420c-a27c-f09ebb1e1565)
		// Type: Rich Text
		// Section: Privacy Configuration
		// Sort Order: 300
		// Source: 

