
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace AtriusHealth.Feature.RichText
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class RichTextItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("e4076c99-8864-41c9-a691-e628331ab7c5");
							public static class FieldIds
		{

			public static readonly string Text = "520e3345-4694-4928-9cbb-cb8204c0fe3f";
}

							public RichTextItem(Item innerItem) : base(innerItem) {}
public static implicit operator RichTextItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new RichTextItem(innerItem) : null;
	}
public static implicit operator Item(RichTextItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Text => InnerItem.Fields[FieldIds.Text];

						}
					}
				





					namespace AtriusHealth.Feature.RichText
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
						using Sitecore.Mvc.Presentation;
						using AtriusHealth.Foundation.Orm;

						public partial class RichTextRenderingParameters : AtriusHealthRenderingParameters
						{
							public static class Fields
		{

			public static string Alignment = "Alignment";

			public static string MaxWidth = "Max Width";
}

							public RichTextRenderingParameters() : base(string.Empty) {}
public RichTextRenderingParameters(string parametersAsQueryString) : base(parametersAsQueryString) {}

							
				public virtual AtriusHealth.Foundation.Enumerations.TextAlignmentItem Alignment => GetItemValue(Fields.Alignment);

				public virtual float MaxWidth => GetFloatValue(Fields.MaxWidth);

						}
					}
				



// AtriusHealth.Feature.RichText.Rich_Text (/sitecore/templates/Feature/Rich Text/Rich Text e4076c99-8864-41c9-a691-e628331ab7c5)
	// Text (520e3345-4694-4928-9cbb-cb8204c0fe3f)
		// Type: Rich Text
		// Section: Content
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.RichText.Rich_Text_Rendering_Parameters (/sitecore/templates/Feature/Rich Text/Rich Text Rendering Parameters a5944469-af21-41d3-84a9-fa7f3544705b)
	// Alignment (2493a7f1-8aa8-4df2-ac90-cd86732f5122)
		// Type: custom=AtriusHealth.Foundation.Enumerations.TextAlignmentItem
		// Section: Display Options
		// Sort Order: 600
		// Source: /sitecore/content/Global Configuration/Enumerations/Text Alignments
	// Max_Width (1b1b6831-ee31-4998-be8d-5e244afbe103)
		// Type: Number
		// Section: Display Options
		// Sort Order: 500
		// Source: 

