---
ID: "7f6326fd-165a-44f1-a99d-a318aed94569"
Parent: "959f7fbb-1e68-4921-bfc7-10119122f6bb"
Template: "239f9cf4-e5a0-44e0-b342-0f32cd4c6d8b"
Path: /sitecore/content/Applications/Content Editor/Context Menues/Default
DB: core
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: tree list
  Value: "{3AEBA8D2-534D-415D-AE7B-EE642B1ED208}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20060215T104631
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20060215T104631
