
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace AtriusHealth.Feature.Account
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class EmailPreferencesItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("61977679-a5da-4791-a6ec-003a99a40ae5");
							public static class FieldIds
		{

			public static readonly string EmailFrequencies = "618cb90e-df16-4287-8d94-55ef2bbe84b1";

			public static readonly string EmailLists = "49dc0619-c5d6-4978-80f8-d688476867ee";
}

							public EmailPreferencesItem(Item innerItem) : base(innerItem) {}
public static implicit operator EmailPreferencesItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new EmailPreferencesItem(innerItem) : null;
	}
public static implicit operator Item(EmailPreferencesItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual MultilistField EmailFrequencies => InnerItem.Fields[FieldIds.EmailFrequencies];

			public virtual MultilistField EmailLists => InnerItem.Fields[FieldIds.EmailLists];

						}
					}
				

					namespace AtriusHealth.Feature.Account
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class InterestsItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("f7a574a1-ffc6-448f-aa92-40d61f2c76c4");
							public static class FieldIds
		{

			public static readonly string Interests = "869ae91d-9f59-4912-bede-3900a421c8ae";
}

							public InterestsItem(Item innerItem) : base(innerItem) {}
public static implicit operator InterestsItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new InterestsItem(innerItem) : null;
	}
public static implicit operator Item(InterestsItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual MultilistField Interests => InnerItem.Fields[FieldIds.Interests];

						}
					}
				

					namespace AtriusHealth.Feature.Account
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _AccountConfigurationItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("69ed1402-6eaf-46ad-b6d6-c3cf273a6e34");
							public static class FieldIds
		{

			public static readonly string LoginPage = "e2a46fd1-6c83-4440-9ff8-c45352284b6c";

			public static readonly string RegistrationConfirmationPage = "909f5624-f12a-4a94-938a-711ccd5fe02b";

			public static readonly string ResetPasswordPage = "adc00f12-ac76-4c41-9750-a75c5f21e16f";
}

							public _AccountConfigurationItem(Item innerItem) : base(innerItem) {}
public static implicit operator _AccountConfigurationItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _AccountConfigurationItem(innerItem) : null;
	}
public static implicit operator Item(_AccountConfigurationItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual LinkField LoginPage => InnerItem.Fields[FieldIds.LoginPage];

			public virtual LinkField RegistrationConfirmationPage => InnerItem.Fields[FieldIds.RegistrationConfirmationPage];

			public virtual LinkField ResetPasswordPage => InnerItem.Fields[FieldIds.ResetPasswordPage];

						}
					}
				







// AtriusHealth.Feature.Account.Email_Preferences (/sitecore/templates/Feature/Account/Email Preferences 61977679-a5da-4791-a6ec-003a99a40ae5)
	// Email_Frequencies (618cb90e-df16-4287-8d94-55ef2bbe84b1)
		// Type: Treelist
		// Section: Configuration
		// Sort Order: 100
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Configuration/Enumerations/*[@@templateid='{AF84DF6A-B5FF-4B6A-996D-17EAE16AEC3F}']
	// Email_Lists (49dc0619-c5d6-4978-80f8-d688476867ee)
		// Type: Treelist
		// Section: Configuration
		// Sort Order: 200
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Configuration/Enumerations/*[@@templateid='{B4229F69-76DC-440C-8D4B-440309341AA1}']

// AtriusHealth.Feature.Account.Interests (/sitecore/templates/Feature/Account/Interests f7a574a1-ffc6-448f-aa92-40d61f2c76c4)
	// Interests (869ae91d-9f59-4912-bede-3900a421c8ae)
		// Type: TreelistEx
		// Section: Configuration
		// Sort Order: 100
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Home/*[@@templateid='{61F2DDC5-111B-406A-AF8B-E37CDC30CA8A}']

// AtriusHealth.Feature.Account._Account_Configuration (/sitecore/templates/Feature/Account/_Account Configuration 69ed1402-6eaf-46ad-b6d6-c3cf273a6e34)
	// Login_Page (e2a46fd1-6c83-4440-9ff8-c45352284b6c)
		// Type: General Link
		// Section: Account Configuration
		// Sort Order: 100
		// Source: 
	// Registration_Confirmation_Page (909f5624-f12a-4a94-938a-711ccd5fe02b)
		// Type: General Link
		// Section: Account Configuration
		// Sort Order: 200
		// Source: 
	// Reset_Password_Page (adc00f12-ac76-4c41-9750-a75c5f21e16f)
		// Type: General Link
		// Section: Account Configuration
		// Sort Order: 300
		// Source: 

