
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Feature.Containers
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class FullWidthBleedContainerItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("1e967a94-9e31-4e7d-9fe2-1daf44e19fea");
							public static class FieldIds
		{
}

							public FullWidthBleedContainerItem(Item innerItem) : base(innerItem) {}
public static implicit operator FullWidthBleedContainerItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new FullWidthBleedContainerItem(innerItem) : null;
	}
public static implicit operator Item(FullWidthBleedContainerItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				







// Thread.Feature.Containers.Full_Width_Bleed_Container (/sitecore/templates/Feature/Containers/Full Width Bleed Container 1e967a94-9e31-4e7d-9fe2-1daf44e19fea)

