
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace AtriusHealth.Project.Common
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ConfigurationFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("9b1048b7-a9ce-4995-a982-a73684bc4dc2");
							public static class FieldIds
		{

			public static readonly string HeaderBrandingTitle = "21ce934b-783b-4864-a152-eeeaf3a6d121";

			public static readonly string HeaderLogoLarge = "a0ca1737-a0d7-4878-9f81-49c1759dc482";

			public static readonly string HeaderLogoSmall = "9afdea09-3395-4ca4-b068-b09b0b0033b2";

			public static readonly string FooterBrandingTitle = "a96facc6-3890-4e57-bb5a-1770a5115cca";

			public static readonly string FooterLogo = "ea671236-6b49-48cf-a30a-c18cc97b3be2";

			public static readonly string ConnectLink = "9658ac80-64d8-4cc2-a466-bd3c3568d11b";

			public static readonly string ConnectStatement = "addd3394-07c6-4f96-b2a2-354c4b9022a1";

			public static readonly string PhoneNumber = "68b134b1-19e5-4664-8fdb-0da0c1750a45";

			public static readonly string TouchToCallPhoneNumber = "96f8b3dc-22dd-4a48-b40c-b3f5f9f32fef";

			public static readonly string CopyrightStatement = "ddbaec9a-cd44-44f2-91db-c8f997a279f5";

			public static readonly string LoginPage = "e2a46fd1-6c83-4440-9ff8-c45352284b6c";

			public static readonly string RegistrationConfirmationPage = "909f5624-f12a-4a94-938a-711ccd5fe02b";

			public static readonly string ResetPasswordPage = "adc00f12-ac76-4c41-9750-a75c5f21e16f";

			public static readonly string Favicon = "8833be50-af2b-4c49-aba1-7d8e2a8af6cc";

			public static readonly string PageTitleSeparator = "f3da5e9e-ddba-46e3-998d-9b12c9e68e5d";

			public static readonly string SiteName = "928de81e-c8bd-4eeb-8f84-2c46a4e9ef76";

			public static readonly string SvgDelimiterName = "a94cf3ac-75ea-4f48-8299-082a9a1aa413";

			public static readonly string _404PageLocation = "be5681b8-5cd7-429e-8676-dd9c73ea965c";

			public static readonly string RobotsText = "81c63ec4-15aa-4280-8379-9a83ae14e4f2";

			public static readonly string AddThisAccountID = "817b2a50-b4b3-4eb4-9313-9fa1565ab181";

			public static readonly string PolicyDescription = "e4e47d7e-9aa2-48d0-8df4-56f8c155e8b8";

			public static readonly string PolicyLink = "9362e660-90c8-4a33-b4c5-b6c5a0580d0f";
}

							public ConfigurationFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator ConfigurationFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ConfigurationFolderItem(innerItem) : null;
	}
public static implicit operator Item(ConfigurationFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField HeaderBrandingTitle => InnerItem.Fields[FieldIds.HeaderBrandingTitle];

			public virtual ImageField HeaderLogoLarge => InnerItem.Fields[FieldIds.HeaderLogoLarge];

			public virtual ImageField HeaderLogoSmall => InnerItem.Fields[FieldIds.HeaderLogoSmall];

			public virtual TextField FooterBrandingTitle => InnerItem.Fields[FieldIds.FooterBrandingTitle];

			public virtual ImageField FooterLogo => InnerItem.Fields[FieldIds.FooterLogo];

			public virtual LinkField ConnectLink => InnerItem.Fields[FieldIds.ConnectLink];

			public virtual TextField ConnectStatement => InnerItem.Fields[FieldIds.ConnectStatement];

			public virtual TextField PhoneNumber => InnerItem.Fields[FieldIds.PhoneNumber];

			public virtual TextField TouchToCallPhoneNumber => InnerItem.Fields[FieldIds.TouchToCallPhoneNumber];

			public virtual TextField CopyrightStatement => InnerItem.Fields[FieldIds.CopyrightStatement];

			public virtual LinkField LoginPage => InnerItem.Fields[FieldIds.LoginPage];

			public virtual LinkField RegistrationConfirmationPage => InnerItem.Fields[FieldIds.RegistrationConfirmationPage];

			public virtual LinkField ResetPasswordPage => InnerItem.Fields[FieldIds.ResetPasswordPage];

			public virtual FileField Favicon => InnerItem.Fields[FieldIds.Favicon];

			public virtual TextField PageTitleSeparator => InnerItem.Fields[FieldIds.PageTitleSeparator];

			public virtual TextField SiteName => InnerItem.Fields[FieldIds.SiteName];

			public virtual TextField SvgDelimiterName => InnerItem.Fields[FieldIds.SvgDelimiterName];

			public virtual LookupField _404PageLocation => InnerItem.Fields[FieldIds._404PageLocation];

			public virtual TextField RobotsText => InnerItem.Fields[FieldIds.RobotsText];

			public virtual TextField AddThisAccountID => InnerItem.Fields[FieldIds.AddThisAccountID];

			public virtual TextField PolicyDescription => InnerItem.Fields[FieldIds.PolicyDescription];

			public virtual LinkField PolicyLink => InnerItem.Fields[FieldIds.PolicyLink];

						}
					}
				

					namespace AtriusHealth.Project.Common
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _PageBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("4fc11a80-88e7-476c-b7c0-7e3d65dcb741");
							public static class FieldIds
		{

			public static readonly string Summary = "19d48702-b149-4a2d-b72d-e3e8b5cf3bcc";

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public _PageBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _PageBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _PageBaseItem(innerItem) : null;
	}
public static implicit operator Item(_PageBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Summary => InnerItem.Fields[FieldIds.Summary];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				

					namespace AtriusHealth.Project.Common
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _PageTitlesBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("2bc36434-6224-4aa7-b5b9-d624307fb875");
							public static class FieldIds
		{

			public static readonly string Title = "91573f05-edb0-43cf-ac81-a6ca06c7fc0d";

			public static readonly string ShortTitle = "10e9213f-9aad-4979-a6a4-912a36275bb9";

			public static readonly string HeaderTitle = "d64a69f6-1317-47a1-a78b-2e22423c8133";

			public static readonly string Subtitle = "cb8dc0b3-f344-4cb0-b9f2-79eb4da005a9";
}

							public _PageTitlesBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _PageTitlesBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _PageTitlesBaseItem(innerItem) : null;
	}
public static implicit operator Item(_PageTitlesBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual TextField ShortTitle => InnerItem.Fields[FieldIds.ShortTitle];

			public virtual TextField HeaderTitle => InnerItem.Fields[FieldIds.HeaderTitle];

			public virtual TextField Subtitle => InnerItem.Fields[FieldIds.Subtitle];

						}
					}
				







// AtriusHealth.Project.Common.Configuration_Folder (/sitecore/templates/Project/Common/Multisite/Configuration Folder 9b1048b7-a9ce-4995-a982-a73684bc4dc2)

// AtriusHealth.Project.Common._Page_Base (/sitecore/templates/Project/Common/Base/_Page Base 4fc11a80-88e7-476c-b7c0-7e3d65dcb741)

// AtriusHealth.Project.Common._Page_Titles_Base (/sitecore/templates/Project/Common/Base/_Page Titles Base 2bc36434-6224-4aa7-b5b9-d624307fb875)

