
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Feature.Metadata
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class MetadataConfigurationItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("3f3a656c-332d-46d6-951e-63fb2d06f8e4");
							public static class FieldIds
		{

			public static readonly string Favicon = "8833be50-af2b-4c49-aba1-7d8e2a8af6cc";

			public static readonly string PageTitleSeparator = "f3da5e9e-ddba-46e3-998d-9b12c9e68e5d";

			public static readonly string SiteName = "928de81e-c8bd-4eeb-8f84-2c46a4e9ef76";
}

							public MetadataConfigurationItem(Item innerItem) : base(innerItem) {}
public static implicit operator MetadataConfigurationItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new MetadataConfigurationItem(innerItem) : null;
	}
public static implicit operator Item(MetadataConfigurationItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual FileField Favicon => InnerItem.Fields[FieldIds.Favicon];

			public virtual TextField PageTitleSeparator => InnerItem.Fields[FieldIds.PageTitleSeparator];

			public virtual TextField SiteName => InnerItem.Fields[FieldIds.SiteName];

						}
					}
				

					namespace Thread.Feature.Metadata
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _IndexBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("e300d2d2-ab70-4876-9c8a-285c681eaf15");
							public static class FieldIds
		{

			public static readonly string NoFollow = "1bd0fef8-5ee5-435b-bde3-a332a0709e8e";

			public static readonly string NoIndex = "497a98de-d47a-4da9-931e-100fc84d5ab1";
}

							public _IndexBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _IndexBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _IndexBaseItem(innerItem) : null;
	}
public static implicit operator Item(_IndexBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual CheckboxField NoFollow => InnerItem.Fields[FieldIds.NoFollow];

			public virtual CheckboxField NoIndex => InnerItem.Fields[FieldIds.NoIndex];

						}
					}
				

					namespace Thread.Feature.Metadata
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class _MetadataBaseItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("c8b2d606-72c1-47cb-b4c3-6d27a3976de0");
							public static class FieldIds
		{

			public static readonly string MetaHtml = "f7504c40-7c68-42c2-be36-8bb61072f21b";
}

							public _MetadataBaseItem(Item innerItem) : base(innerItem) {}
public static implicit operator _MetadataBaseItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new _MetadataBaseItem(innerItem) : null;
	}
public static implicit operator Item(_MetadataBaseItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField MetaHtml => InnerItem.Fields[FieldIds.MetaHtml];

						}
					}
				







// Thread.Feature.Metadata.Metadata_Configuration (/sitecore/templates/Feature/Metadata/Metadata Configuration 3f3a656c-332d-46d6-951e-63fb2d06f8e4)
	// Favicon (8833be50-af2b-4c49-aba1-7d8e2a8af6cc)
		// Type: File
		// Section: Header
		// Sort Order: 400
		// Source: /sitecore/media library
	// Page_Title_Separator (f3da5e9e-ddba-46e3-998d-9b12c9e68e5d)
		// Type: Single-Line Text
		// Section: Metadata Configuration
		// Sort Order: 400
		// Source: 
	// Site_Name (928de81e-c8bd-4eeb-8f84-2c46a4e9ef76)
		// Type: Single-Line Text
		// Section: Metadata Configuration
		// Sort Order: 300
		// Source: 

// Thread.Feature.Metadata._Index_Base (/sitecore/templates/Feature/Metadata/_Index Base e300d2d2-ab70-4876-9c8a-285c681eaf15)
	// No_Follow (1bd0fef8-5ee5-435b-bde3-a332a0709e8e)
		// Type: Checkbox
		// Section: Index
		// Sort Order: 200
		// Source: 
	// No_Index (497a98de-d47a-4da9-931e-100fc84d5ab1)
		// Type: Checkbox
		// Section: Index
		// Sort Order: 100
		// Source: 

// Thread.Feature.Metadata._Metadata_Base (/sitecore/templates/Feature/Metadata/_Metadata Base c8b2d606-72c1-47cb-b4c3-6d27a3976de0)
	// Meta_Html (f7504c40-7c68-42c2-be36-8bb61072f21b)
		// Type: Multi-Line Text
		// Section: Metadata
		// Sort Order: 100
		// Source: 

