export const contactFormData = {
  name: {
    autocomplete: "name",
    error: false,
    errorMsg: "Please enter your full name",
    label: "First Name",
    name: "name",
    placeholder: "e.g. John Doe",
    required: true,
    type: "text",
    validationType: "text",
  },
  email: {
    autocomplete: "email",
    error: false,
    errorMsg: "Please enter a valid email address",
    label: "Email Address",
    name: "email",
    placeholder: "your.name@example.com",
    required: true,
    type: "email",
    validationType: "email",
  },
  subject: {
    autocomplete: "",
    error: false,
    errorMsg: "Please enter a subject for your message",
    label: "Subject",
    name: "subject",
    placeholder: "",
    required: true,
    type: "text",
    validationType: "text",
  },
  message: {
    error: false,
    errorMsg: "Please enter a message for you inquiry",
    label: "Message",
    name: "message",
    required: true,
  },
};

export const contactErrorData = {
  name: {
    autocomplete: "name",
    error: true,
    errorMsg: "Please enter your full name",
    label: "First Name",
    name: "name",
    placeholder: "e.g. John Doe",
    required: true,
    type: "text",
    validationType: "text",
  },
  email: {
    autocomplete: "email",
    error: true,
    errorMsg: "Please enter a valid email address",
    label: "Email Address",
    name: "email",
    placeholder: "your.name@example.com",
    required: true,
    type: "email",
    validationType: "email",
  },
  subject: {
    autocomplete: "",
    error: true,
    errorMsg: "Please enter a subject for your message",
    label: "Subject",
    name: "subject",
    placeholder: "",
    required: true,
    type: "text",
    validationType: "text",
  },
  message: {
    error: true,
    errorMsg: "Please enter a message for you inquiry",
    label: "Message",
    name: "message",
    required: true,
  },
};

export const formForgotPasswordData = {
  email: {
    autocomplete: "",
    error: false,
    errorMsg: "Please enter a valid email address",
    label: "Email Address",
    name: "email",
    placeholder: "your.name@example.com",
    required: true,
    showPassword: false,
    type: "email",
    validationType: "email",
  },
};

export const forgotPasswordErrorData = {
  email: {
    autocomplete: "",
    error: true,
    errorMsg:
      "Hmm, this email address is not recognized in our database. Please check the address and try again.",
    label: "Email Address",
    name: "email",
    placeholder: "your.name@example.com",
    required: true,
    showPassword: false,
    type: "email",
    validationType: "email",
  },
};

export const loginData = {
  username: {
    autocomplete: "",
    error: false,
    errorMsg: "Username or email address is required",
    label: "Username or email address",
    name: "username",
    placeholder: "",
    required: true,
    showPassword: false,
    type: "text",
    validationType: "text",
  },
  password: {
    autocomplete: "new-password",
    error: false,
    errorMsg: "Password is required",
    label: "Password",
    name: "password",
    placeholder: "",
    required: true,
    showPassword: true,
    type: "password",
    validationType: "password",
  },
  button: {
    btn_text: "Sign in",
    btn_type: "primary",
  },
};

export const registrationData = {
  formTitle: "Not a member yet? Sign up!",
  first: {
    autocomplete: "given-name",
    error: false,
    errorMsg: "First Name is required",
    label: "First Name",
    name: "fname",
    placeholder: "e.g. John",
    required: true,
    type: "text",
    validationType: "text",
  },
  last: {
    autocomplete: "family-name",
    error: false,
    errorMsg: "Last Name is required",
    label: "Last Name",
    name: "lname",
    placeholder: "e.g. Doe",
    required: true,
    type: "text",
    validationType: "text",
  },
  email: {
    autocomplete: "email",
    error: true,
    errorMsg: "Email Address is required",
    label: "Email Address",
    name: "email",
    placeholder: "your.name@example.com",
    required: true,
    type: "email",
    validationType: "email",
  },
  password: {
    autocomplete: "new-password",
    error: false,
    errorMsg: "Password is required",
    label: "Password",
    name: "password",
    placeholder: "6-20 characters (A-Z, a-z, 0-9)",
    required: true,
    type: "password",
    validationType: "password",
  },
  passwordMatch: {
    autocomplete: "new-password",
    error: true,
    errorMsg: "Passwords don't match",
    label: "Re-enter Password",
    name: "password-match",
    placeholder: "",
    required: true,
    type: "password",
    validationType: "passwordMatch",
  },
};

export const resetPasswordData = {
  password: {
    autocomplete: "new-password",
    error: false,
    errorMsg: "Password is required",
    label: "Password",
    name: "password",
    placeholder: "6-20 characters (A-Z, a-z, 0-9)",
    required: true,
    type: "password",
    validationType: "password",
  },
  passwordMatch: {
    autocomplete: "new-password",
    error: true,
    errorMsg: "Passwords don't match",
    label: "Re-enter Password",
    name: "password-match",
    placeholder: "",
    required: true,
    type: "password",
    validationType: "passwordMatch",
  },
};
