
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

namespace AtriusHealth.Feature.Search
{
  using Sitecore.Data;
  using Sitecore.Data.Fields;
  using Sitecore.Data.Items;

  public partial class FeaturedResultsItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("80a8ad76-8ee3-483b-a43c-9fe29ca77938");
							public static class FieldIds
		{

			public static readonly string FeaturedItems = "300f4fbf-afb4-43d5-afea-30561fb789aa";

			public static readonly string Keywords = "2e58181a-1231-4c55-a7b8-bc65efde792b";
}

							public FeaturedResultsItem(Item innerItem) : base(innerItem) {}
public static implicit operator FeaturedResultsItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new FeaturedResultsItem(innerItem) : null;
	}
public static implicit operator Item(FeaturedResultsItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual MultilistField FeaturedItems => InnerItem.Fields[FieldIds.FeaturedItems];

			public virtual TextField Keywords => InnerItem.Fields[FieldIds.Keywords];

						}
					}
				

					namespace AtriusHealth.Feature.Search
{
  using Sitecore.Data;
  using Sitecore.Data.Items;

  public partial class FeaturedResultsFolderItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("d791a14e-0f21-4461-a457-1eda601795b5");
							public static class FieldIds
		{
}

							public FeaturedResultsFolderItem(Item innerItem) : base(innerItem) {}
public static implicit operator FeaturedResultsFolderItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new FeaturedResultsFolderItem(innerItem) : null;
	}
public static implicit operator Item(FeaturedResultsFolderItem customItem)
	{
		return customItem?.InnerItem;
	}

							
						}
					}
				

					namespace AtriusHealth.Feature.Search
{
  using Sitecore.Data;
  using Sitecore.Data.Fields;
  using Sitecore.Data.Items;

  public partial class SearchResultsItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("45c047e7-a01e-4e09-ab47-a76dc25f2f0c");
							public static class FieldIds
		{

			public static readonly string FeaturedResultsEndpoint = "39fc0c16-7a0a-4458-8f51-57fecd5d5477";

			public static readonly string NumberOfItems = "642ab2a6-8b71-4553-8dfc-f737362d0779";

			public static readonly string SearchResultsFormat = "1b853b14-36cd-4fee-89e1-2f574c6e1dab";
}

							public SearchResultsItem(Item innerItem) : base(innerItem) {}
public static implicit operator SearchResultsItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new SearchResultsItem(innerItem) : null;
	}
public static implicit operator Item(SearchResultsItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual TextField FeaturedResultsEndpoint => InnerItem.Fields[FieldIds.FeaturedResultsEndpoint];

			public virtual LookupField NumberOfItems => InnerItem.Fields[FieldIds.NumberOfItems];

			public virtual LookupField SearchResultsFormat => InnerItem.Fields[FieldIds.SearchResultsFormat];

						}
					}
				





					namespace AtriusHealth.Feature.Search
{
  using Sitecore.Data.Items;
  using AtriusHealth.Foundation.Orm;

  public partial class SearchFacetsRenderingParameters : AtriusHealthRenderingParameters
						{
							public static class Fields
		{

			public static string MobileTransition = "Mobile Transition";
}

							public SearchFacetsRenderingParameters() : base(string.Empty) {}
public SearchFacetsRenderingParameters(string parametersAsQueryString) : base(parametersAsQueryString) {}

							
				public virtual Item MobileTransition => GetItemValue(Fields.MobileTransition);

						}
					}
				



// AtriusHealth.Feature.Search.Featured_Results (/sitecore/templates/Feature/Search/Featured Results 80a8ad76-8ee3-483b-a43c-9fe29ca77938)
	// Featured_Items (300f4fbf-afb4-43d5-afea-30561fb789aa)
		// Type: TreelistEx
		// Section: Featured Items
		// Sort Order: 100
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Home
	// Keywords (2e58181a-1231-4c55-a7b8-bc65efde792b)
		// Type: Multi-Line Text
		// Section: Keywords
		// Sort Order: 100
		// Source: 

// AtriusHealth.Feature.Search.Featured_Results_Folder (/sitecore/templates/Feature/Search/Featured Results Folder d791a14e-0f21-4461-a457-1eda601795b5)

// AtriusHealth.Feature.Search.Search_Facets_Rendering_Parameters (/sitecore/templates/Feature/Search/Search Facets Rendering Parameters 1ae5d59f-367f-4745-bf6f-a9ff7ae6bea7)
	// Mobile_Transition (08cd4522-7f82-4567-803a-eac6e67cf9e5)
		// Type: Droplink
		// Section: Display Options
		// Sort Order: 100
		// Source: /sitecore/system/Modules/Search/Enumerations/Transition Directions

// AtriusHealth.Feature.Search.Search_Results (/sitecore/templates/Feature/Search/Search Results 45c047e7-a01e-4e09-ab47-a76dc25f2f0c)
	// Featured_Results_Endpoint (39fc0c16-7a0a-4458-8f51-57fecd5d5477)
		// Type: Single-Line Text
		// Section: Configuration
		// Sort Order: 300
		// Source: 
	// Number_Of_Items (642ab2a6-8b71-4553-8dfc-f737362d0779)
		// Type: Droplink
		// Section: Configuration
		// Sort Order: 200
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Configuration/Enumerations/Number of Items/*
	// Search_Results_Format (1b853b14-36cd-4fee-89e1-2f574c6e1dab)
		// Type: Droplink
		// Section: Configuration
		// Sort Order: 100
		// Source: /sitecore/system/Modules/Search/Enumerations/Results Formats

