
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable All

					namespace Thread.Feature.Listing
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ContentListingItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("4943da38-e705-4ee8-a4bc-973e31304f3a");
							public static class FieldIds
		{

			public static readonly string NumberOfItems = "caed5a05-b1fb-40c7-9ea0-d1031b1a70c7";

			public static readonly string Title = "015ca08f-41fa-4c84-9f9d-294abf42d238";
}

							public ContentListingItem(Item innerItem) : base(innerItem) {}
public static implicit operator ContentListingItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ContentListingItem(innerItem) : null;
	}
public static implicit operator Item(ContentListingItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual LookupField NumberOfItems => InnerItem.Fields[FieldIds.NumberOfItems];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				

					namespace Thread.Feature.Listing
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class ContentListingItemItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("f71b9edb-b484-405c-a84f-e8fd17db6ca9");
							public static class FieldIds
		{

			public static readonly string Date = "c6fd88bd-192d-43af-b607-1076dcc4905d";

			public static readonly string Description = "a7bdcd32-7f92-47a9-8cff-85870d266d27";

			public static readonly string Image = "f1779063-dc55-472a-977b-32a61ce57190";

			public static readonly string Link = "8c8df1dd-015c-4ee9-b24c-4f2daaf118c9";

			public static readonly string Title = "81b6d8c9-cc77-41db-bd64-e6fbc7a5183b";

			public static readonly string ContentType = "d7b9c27c-79e3-42a7-9b46-bff652ef0981";

			public static readonly string People = "bef10252-ea97-4433-a7e3-d924796e3950";
}

							public ContentListingItemItem(Item innerItem) : base(innerItem) {}
public static implicit operator ContentListingItemItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new ContentListingItemItem(innerItem) : null;
	}
public static implicit operator Item(ContentListingItemItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual DateField Date => InnerItem.Fields[FieldIds.Date];

			public virtual TextField Description => InnerItem.Fields[FieldIds.Description];

			public virtual ImageField Image => InnerItem.Fields[FieldIds.Image];

			public virtual LinkField Link => InnerItem.Fields[FieldIds.Link];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

			public virtual LookupField ContentType => InnerItem.Fields[FieldIds.ContentType];

			public virtual MultilistField People => InnerItem.Fields[FieldIds.People];

						}
					}
				

					namespace Thread.Feature.Listing
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
							
						public partial class DynamicContentListingItem : CustomItem
						{
							
			public static readonly ID TemplateId = new ID("b0bb95b3-6115-4a24-afd4-9846e59093a6");
							public static class FieldIds
		{

			public static readonly string ContentTypesDisplayed = "11a2a15b-52c4-4dc6-bb76-1150fcf05e69";

			public static readonly string FiltersDisplayed = "bdb4079f-841b-45f6-b590-27aa702d2b99";

			public static readonly string NumberOfItems = "ffdd524a-b146-47af-a08c-a531c6d638cd";

			public static readonly string SortMethod = "cf77e1f2-c995-4fe2-a30c-61470ec48c1f";

			public static readonly string TaxonomyOverride = "eac819a5-4d8d-428c-ba3b-ae66d99a6f7a";

			public static readonly string Title = "8aed5cfc-3cc1-4f92-96d0-8b20a9081a0e";
}

							public DynamicContentListingItem(Item innerItem) : base(innerItem) {}
public static implicit operator DynamicContentListingItem(Item innerItem)
	{
		return innerItem != null && innerItem.DescendsFrom(TemplateId) ? new DynamicContentListingItem(innerItem) : null;
	}
public static implicit operator Item(DynamicContentListingItem customItem)
	{
		return customItem?.InnerItem;
	}

							
			public virtual MultilistField ContentTypesDisplayed => InnerItem.Fields[FieldIds.ContentTypesDisplayed];

			public virtual MultilistField FiltersDisplayed => InnerItem.Fields[FieldIds.FiltersDisplayed];

			public virtual LookupField NumberOfItems => InnerItem.Fields[FieldIds.NumberOfItems];

			public virtual LookupField SortMethod => InnerItem.Fields[FieldIds.SortMethod];

			public virtual MultilistField TaxonomyOverride => InnerItem.Fields[FieldIds.TaxonomyOverride];

			public virtual TextField Title => InnerItem.Fields[FieldIds.Title];

						}
					}
				





					namespace Thread.Feature.Listing
					{
						using Sitecore.Data;
						using Sitecore.Data.Fields;
						using Sitecore.Data.Items;
						using Sitecore.Mvc.Presentation;
						using Thread.Foundation.Orm;

						public partial class DynamicContentListingRenderingParameters : ThreadRenderingParameters
						{
							public static class Fields
		{

			public static string DisplayContentTypeLabels = "Display Content Type Labels";

			public static string DisplayDates = "Display Dates";

			public static string DisplayImages = "Display Images";

			public static string DisplaySummaries = "Display Summaries";
}

							public DynamicContentListingRenderingParameters() : base(string.Empty) {}
public DynamicContentListingRenderingParameters(string parametersAsQueryString) : base(parametersAsQueryString) {}

							
				public virtual bool DisplayContentTypeLabels => GetBoolValue(Fields.DisplayContentTypeLabels);

				public virtual bool DisplayDates => GetBoolValue(Fields.DisplayDates);

				public virtual Thread.Foundation.Enumerations.RatioItem DisplayImages => GetItemValue(Fields.DisplayImages);

				public virtual bool DisplaySummaries => GetBoolValue(Fields.DisplaySummaries);

						}
					}
				



// Thread.Feature.Listing.Content_Listing (/sitecore/templates/Feature/Listing/Content Listing 4943da38-e705-4ee8-a4bc-973e31304f3a)
	// Number_Of_Items (caed5a05-b1fb-40c7-9ea0-d1031b1a70c7)
		// Type: Droplink
		// Section: Display Options
		// Sort Order: 100
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Configuration/Enumerations/Number of Items/*
	// Title (015ca08f-41fa-4c84-9f9d-294abf42d238)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

// Thread.Feature.Listing.Content_Listing_Item (/sitecore/templates/Feature/Listing/Content Listing Item f71b9edb-b484-405c-a84f-e8fd17db6ca9)
	// Date (c6fd88bd-192d-43af-b607-1076dcc4905d)
		// Type: Date
		// Section: Date
		// Sort Order: 100
		// Source: 
	// Description (a7bdcd32-7f92-47a9-8cff-85870d266d27)
		// Type: Multi-Line Text
		// Section: Text
		// Sort Order: 100
		// Source: 
	// Image (f1779063-dc55-472a-977b-32a61ce57190)
		// Type: Image
		// Section: Image
		// Sort Order: 100
		// Source: 
	// Link (8c8df1dd-015c-4ee9-b24c-4f2daaf118c9)
		// Type: General Link
		// Section: Link
		// Sort Order: 100
		// Source: 
	// Title (81b6d8c9-cc77-41db-bd64-e6fbc7a5183b)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

// Thread.Feature.Listing.Dynamic_Content_Listing (/sitecore/templates/Feature/Listing/Dynamic Content Listing b0bb95b3-6115-4a24-afd4-9846e59093a6)
	// Content_Types_Displayed (11a2a15b-52c4-4dc6-bb76-1150fcf05e69)
		// Type: Multilist with Search
		// Section: Configuration
		// Sort Order: 100
		// Source: StartSearchLocation=query:ancestor-or-self::*[@@templateid->'{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Home/Taxonomy/#Content Types#&TemplateFilter={2DCA937A-9634-4D0D-9A27-8B8D9ED3D99B}
	// Filters_Displayed (bdb4079f-841b-45f6-b590-27aa702d2b99)
		// Type: TreelistEx
		// Section: Configuration
		// Sort Order: 500
		// Source: /sitecore/system/Modules/Search/Filters
	// Number_Of_Items (ffdd524a-b146-47af-a08c-a531c6d638cd)
		// Type: Droplink
		// Section: Configuration
		// Sort Order: 400
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Configuration/Enumerations/Number of Items/*
	// Sort_Method (cf77e1f2-c995-4fe2-a30c-61470ec48c1f)
		// Type: Droplink
		// Section: Configuration
		// Sort Order: 300
		// Source: /sitecore/system/Modules/Search/Sort Options
	// Taxonomy_Override (eac819a5-4d8d-428c-ba3b-ae66d99a6f7a)
		// Type: TreelistEx
		// Section: Configuration
		// Sort Order: 200
		// Source: query:ancestor-or-self::*[@@templateid='{98AC8506-0017-4964-81A9-19B76FA9EE98}']/Home/Taxonomy
	// Title (8aed5cfc-3cc1-4f92-96d0-8b20a9081a0e)
		// Type: Single-Line Text
		// Section: Title
		// Sort Order: 100
		// Source: 

// Thread.Feature.Listing.Dynamic_Content_Listing_Rendering_Parameters (/sitecore/templates/Feature/Listing/Dynamic Content Listing Rendering Parameters cdce947d-d086-4163-bf35-2761663976d7)
	// Display_Content_Type_Labels (290723e9-f36a-4ec9-ad0d-765bed940aaa)
		// Type: Checkbox
		// Section: Display Options
		// Sort Order: 200
		// Source: 
	// Display_Dates (f0a1fde7-2914-4d08-9cb0-11b49b7577f6)
		// Type: Checkbox
		// Section: Display Options
		// Sort Order: 100
		// Source: 
	// Display_Images (23241de5-760d-420f-83cc-3a0f1ef26369)
		// Type: custom=Thread.Foundation.Enumerations.RatioItem
		// Section: Display Options
		// Sort Order: 400
		// Source: /sitecore/content/Global Configuration/Enumerations/Ratios
	// Display_Summaries (e1ef98ef-04a4-4db2-8093-6e07bbd64b64)
		// Type: Checkbox
		// Section: Display Options
		// Sort Order: 300
		// Source: 

